-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcJ5KNPLcaK9GDo5X
3MlfjjeVUSkA2DlOWFgjRwtC/6OgCgYIKoZIzj0DAQehRANCAARJeS1lx1dAGD1Z
rurhh7iHUcaLlUr5nch8+aE3VlYzg4GjwfvOM2iFTXsPKKQajIvTns5MEtpVWTSK
a/cQ59oX
-----END PRIVATE KEY-----