// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ForeignInvasionDB.proto

package protocol;

public final class ForeignInvasionDB {
  private ForeignInvasionDB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DB_ForeignInvasionPlayerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DB_ForeignInvasionPlayerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *&lt;buildingId
     * </pre>
     *
     * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
     */
    int getBuildingsInfoCount();
    /**
     * <pre>
     *&lt;buildingId
     * </pre>
     *
     * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
     */
    boolean containsBuildingsInfo(
        int key);
    /**
     * Use {@link #getBuildingsInfoMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo>
    getBuildingsInfo();
    /**
     * <pre>
     *&lt;buildingId
     * </pre>
     *
     * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
     */
    java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo>
    getBuildingsInfoMap();
    /**
     * <pre>
     *&lt;buildingId
     * </pre>
     *
     * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
     */

    protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo getBuildingsInfoOrDefault(
        int key,
        protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo defaultValue);
    /**
     * <pre>
     *&lt;buildingId
     * </pre>
     *
     * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
     */

    protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo getBuildingsInfoOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code DB_ForeignInvasionPlayerInfo}
   */
  public  static final class DB_ForeignInvasionPlayerInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DB_ForeignInvasionPlayerInfo)
      DB_ForeignInvasionPlayerInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DB_ForeignInvasionPlayerInfo.newBuilder() to construct.
    private DB_ForeignInvasionPlayerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DB_ForeignInvasionPlayerInfo() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DB_ForeignInvasionPlayerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                buildingsInfo_ = com.google.protobuf.MapField.newMapField(
                    BuildingsInfoDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo>
              buildingsInfo__ = input.readMessage(
                  BuildingsInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              buildingsInfo_.getMutableMap().put(
                  buildingsInfo__.getKey(), buildingsInfo__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionPlayerInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetBuildingsInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionPlayerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo.class, protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo.Builder.class);
    }

    public static final int BUILDINGSINFO_FIELD_NUMBER = 1;
    private static final class BuildingsInfoDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo>newDefaultInstance(
                  protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionPlayerInfo_BuildingsInfoEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> buildingsInfo_;
    private com.google.protobuf.MapField<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo>
    internalGetBuildingsInfo() {
      if (buildingsInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            BuildingsInfoDefaultEntryHolder.defaultEntry);
      }
      return buildingsInfo_;
    }

    public int getBuildingsInfoCount() {
      return internalGetBuildingsInfo().getMap().size();
    }
    /**
     * <pre>
     *&lt;buildingId
     * </pre>
     *
     * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
     */

    public boolean containsBuildingsInfo(
        int key) {
      
      return internalGetBuildingsInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getBuildingsInfoMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> getBuildingsInfo() {
      return getBuildingsInfoMap();
    }
    /**
     * <pre>
     *&lt;buildingId
     * </pre>
     *
     * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
     */

    public java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> getBuildingsInfoMap() {
      return internalGetBuildingsInfo().getMap();
    }
    /**
     * <pre>
     *&lt;buildingId
     * </pre>
     *
     * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
     */

    public protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo getBuildingsInfoOrDefault(
        int key,
        protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo defaultValue) {
      
      java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> map =
          internalGetBuildingsInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *&lt;buildingId
     * </pre>
     *
     * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
     */

    public protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo getBuildingsInfoOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> map =
          internalGetBuildingsInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetBuildingsInfo(),
          BuildingsInfoDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> entry
           : internalGetBuildingsInfo().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo>
        buildingsInfo__ = BuildingsInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, buildingsInfo__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo)) {
        return super.equals(obj);
      }
      protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo other = (protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo) obj;

      boolean result = true;
      result = result && internalGetBuildingsInfo().equals(
          other.internalGetBuildingsInfo());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetBuildingsInfo().getMap().isEmpty()) {
        hash = (37 * hash) + BUILDINGSINFO_FIELD_NUMBER;
        hash = (53 * hash) + internalGetBuildingsInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DB_ForeignInvasionPlayerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DB_ForeignInvasionPlayerInfo)
        protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionPlayerInfo_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetBuildingsInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableBuildingsInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionPlayerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo.class, protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo.Builder.class);
      }

      // Construct using protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableBuildingsInfo().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionPlayerInfo_descriptor;
      }

      public protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo getDefaultInstanceForType() {
        return protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo.getDefaultInstance();
      }

      public protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo build() {
        protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo buildPartial() {
        protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo result = new protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo(this);
        int from_bitField0_ = bitField0_;
        result.buildingsInfo_ = internalGetBuildingsInfo();
        result.buildingsInfo_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo) {
          return mergeFrom((protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo other) {
        if (other == protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo.getDefaultInstance()) return this;
        internalGetMutableBuildingsInfo().mergeFrom(
            other.internalGetBuildingsInfo());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> buildingsInfo_;
      private com.google.protobuf.MapField<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo>
      internalGetBuildingsInfo() {
        if (buildingsInfo_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              BuildingsInfoDefaultEntryHolder.defaultEntry);
        }
        return buildingsInfo_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo>
      internalGetMutableBuildingsInfo() {
        onChanged();;
        if (buildingsInfo_ == null) {
          buildingsInfo_ = com.google.protobuf.MapField.newMapField(
              BuildingsInfoDefaultEntryHolder.defaultEntry);
        }
        if (!buildingsInfo_.isMutable()) {
          buildingsInfo_ = buildingsInfo_.copy();
        }
        return buildingsInfo_;
      }

      public int getBuildingsInfoCount() {
        return internalGetBuildingsInfo().getMap().size();
      }
      /**
       * <pre>
       *&lt;buildingId
       * </pre>
       *
       * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
       */

      public boolean containsBuildingsInfo(
          int key) {
        
        return internalGetBuildingsInfo().getMap().containsKey(key);
      }
      /**
       * Use {@link #getBuildingsInfoMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> getBuildingsInfo() {
        return getBuildingsInfoMap();
      }
      /**
       * <pre>
       *&lt;buildingId
       * </pre>
       *
       * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
       */

      public java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> getBuildingsInfoMap() {
        return internalGetBuildingsInfo().getMap();
      }
      /**
       * <pre>
       *&lt;buildingId
       * </pre>
       *
       * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
       */

      public protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo getBuildingsInfoOrDefault(
          int key,
          protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo defaultValue) {
        
        java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> map =
            internalGetBuildingsInfo().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *&lt;buildingId
       * </pre>
       *
       * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
       */

      public protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo getBuildingsInfoOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> map =
            internalGetBuildingsInfo().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearBuildingsInfo() {
        internalGetMutableBuildingsInfo().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *&lt;buildingId
       * </pre>
       *
       * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
       */

      public Builder removeBuildingsInfo(
          int key) {
        
        internalGetMutableBuildingsInfo().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo>
      getMutableBuildingsInfo() {
        return internalGetMutableBuildingsInfo().getMutableMap();
      }
      /**
       * <pre>
       *&lt;buildingId
       * </pre>
       *
       * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
       */
      public Builder putBuildingsInfo(
          int key,
          protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableBuildingsInfo().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *&lt;buildingId
       * </pre>
       *
       * <code>map&lt;int32, .DB_ForeignInvasionBuildingPlayerInfo&gt; buildingsInfo = 1;</code>
       */

      public Builder putAllBuildingsInfo(
          java.util.Map<java.lang.Integer, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo> values) {
        internalGetMutableBuildingsInfo().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DB_ForeignInvasionPlayerInfo)
    }

    // @@protoc_insertion_point(class_scope:DB_ForeignInvasionPlayerInfo)
    private static final protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo();
    }

    public static protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DB_ForeignInvasionPlayerInfo>
        PARSER = new com.google.protobuf.AbstractParser<DB_ForeignInvasionPlayerInfo>() {
      public DB_ForeignInvasionPlayerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DB_ForeignInvasionPlayerInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DB_ForeignInvasionPlayerInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DB_ForeignInvasionPlayerInfo> getParserForType() {
      return PARSER;
    }

    public protocol.ForeignInvasionDB.DB_ForeignInvasionPlayerInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DB_ForeignInvasionBuildingPlayerInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DB_ForeignInvasionBuildingPlayerInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *建筑Id
     * </pre>
     *
     * <code>int32 buildingId = 1;</code>
     */
    int getBuildingId();

    /**
     * <pre>
     *当前波次
     * </pre>
     *
     * <code>int32 curWave = 2;</code>
     */
    int getCurWave();

    /**
     * <pre>
     *当前波次怪物阵容
     * </pre>
     *
     * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
     */
    java.util.List<protocol.Battle.BattlePetData> 
        getCurWaveMonsterInfoList();
    /**
     * <pre>
     *当前波次怪物阵容
     * </pre>
     *
     * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
     */
    protocol.Battle.BattlePetData getCurWaveMonsterInfo(int index);
    /**
     * <pre>
     *当前波次怪物阵容
     * </pre>
     *
     * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
     */
    int getCurWaveMonsterInfoCount();
    /**
     * <pre>
     *当前波次怪物阵容
     * </pre>
     *
     * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
     */
    java.util.List<? extends protocol.Battle.BattlePetDataOrBuilder> 
        getCurWaveMonsterInfoOrBuilderList();
    /**
     * <pre>
     *当前波次怪物阵容
     * </pre>
     *
     * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
     */
    protocol.Battle.BattlePetDataOrBuilder getCurWaveMonsterInfoOrBuilder(
        int index);

    /**
     * <pre>
     *备战宠物剩余血量
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
     */
    int getPetsRemainHpCount();
    /**
     * <pre>
     *备战宠物剩余血量
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
     */
    boolean containsPetsRemainHp(
        java.lang.String key);
    /**
     * Use {@link #getPetsRemainHpMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet>
    getPetsRemainHp();
    /**
     * <pre>
     *备战宠物剩余血量
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
     */
    java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet>
    getPetsRemainHpMap();
    /**
     * <pre>
     *备战宠物剩余血量
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
     */

    protocol.Battle.BattleRemainPet getPetsRemainHpOrDefault(
        java.lang.String key,
        protocol.Battle.BattleRemainPet defaultValue);
    /**
     * <pre>
     *备战宠物剩余血量
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
     */

    protocol.Battle.BattleRemainPet getPetsRemainHpOrThrow(
        java.lang.String key);

    /**
     * <pre>
     *当前关卡怪物
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
     */
    int getMonsterRemainHpCount();
    /**
     * <pre>
     *当前关卡怪物
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
     */
    boolean containsMonsterRemainHp(
        java.lang.String key);
    /**
     * Use {@link #getMonsterRemainHpMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet>
    getMonsterRemainHp();
    /**
     * <pre>
     *当前关卡怪物
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
     */
    java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet>
    getMonsterRemainHpMap();
    /**
     * <pre>
     *当前关卡怪物
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
     */

    protocol.Battle.BattleRemainPet getMonsterRemainHpOrDefault(
        java.lang.String key,
        protocol.Battle.BattleRemainPet defaultValue);
    /**
     * <pre>
     *当前关卡怪物
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
     */

    protocol.Battle.BattleRemainPet getMonsterRemainHpOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code DB_ForeignInvasionBuildingPlayerInfo}
   */
  public  static final class DB_ForeignInvasionBuildingPlayerInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DB_ForeignInvasionBuildingPlayerInfo)
      DB_ForeignInvasionBuildingPlayerInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DB_ForeignInvasionBuildingPlayerInfo.newBuilder() to construct.
    private DB_ForeignInvasionBuildingPlayerInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DB_ForeignInvasionBuildingPlayerInfo() {
      buildingId_ = 0;
      curWave_ = 0;
      curWaveMonsterInfo_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DB_ForeignInvasionBuildingPlayerInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              buildingId_ = input.readInt32();
              break;
            }
            case 16: {

              curWave_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                curWaveMonsterInfo_ = new java.util.ArrayList<protocol.Battle.BattlePetData>();
                mutable_bitField0_ |= 0x00000004;
              }
              curWaveMonsterInfo_.add(
                  input.readMessage(protocol.Battle.BattlePetData.parser(), extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                petsRemainHp_ = com.google.protobuf.MapField.newMapField(
                    PetsRemainHpDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, protocol.Battle.BattleRemainPet>
              petsRemainHp__ = input.readMessage(
                  PetsRemainHpDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              petsRemainHp_.getMutableMap().put(
                  petsRemainHp__.getKey(), petsRemainHp__.getValue());
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                monsterRemainHp_ = com.google.protobuf.MapField.newMapField(
                    MonsterRemainHpDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, protocol.Battle.BattleRemainPet>
              monsterRemainHp__ = input.readMessage(
                  MonsterRemainHpDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              monsterRemainHp_.getMutableMap().put(
                  monsterRemainHp__.getKey(), monsterRemainHp__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          curWaveMonsterInfo_ = java.util.Collections.unmodifiableList(curWaveMonsterInfo_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionBuildingPlayerInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 4:
          return internalGetPetsRemainHp();
        case 5:
          return internalGetMonsterRemainHp();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionBuildingPlayerInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo.class, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo.Builder.class);
    }

    private int bitField0_;
    public static final int BUILDINGID_FIELD_NUMBER = 1;
    private int buildingId_;
    /**
     * <pre>
     *建筑Id
     * </pre>
     *
     * <code>int32 buildingId = 1;</code>
     */
    public int getBuildingId() {
      return buildingId_;
    }

    public static final int CURWAVE_FIELD_NUMBER = 2;
    private int curWave_;
    /**
     * <pre>
     *当前波次
     * </pre>
     *
     * <code>int32 curWave = 2;</code>
     */
    public int getCurWave() {
      return curWave_;
    }

    public static final int CURWAVEMONSTERINFO_FIELD_NUMBER = 3;
    private java.util.List<protocol.Battle.BattlePetData> curWaveMonsterInfo_;
    /**
     * <pre>
     *当前波次怪物阵容
     * </pre>
     *
     * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
     */
    public java.util.List<protocol.Battle.BattlePetData> getCurWaveMonsterInfoList() {
      return curWaveMonsterInfo_;
    }
    /**
     * <pre>
     *当前波次怪物阵容
     * </pre>
     *
     * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
     */
    public java.util.List<? extends protocol.Battle.BattlePetDataOrBuilder> 
        getCurWaveMonsterInfoOrBuilderList() {
      return curWaveMonsterInfo_;
    }
    /**
     * <pre>
     *当前波次怪物阵容
     * </pre>
     *
     * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
     */
    public int getCurWaveMonsterInfoCount() {
      return curWaveMonsterInfo_.size();
    }
    /**
     * <pre>
     *当前波次怪物阵容
     * </pre>
     *
     * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
     */
    public protocol.Battle.BattlePetData getCurWaveMonsterInfo(int index) {
      return curWaveMonsterInfo_.get(index);
    }
    /**
     * <pre>
     *当前波次怪物阵容
     * </pre>
     *
     * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
     */
    public protocol.Battle.BattlePetDataOrBuilder getCurWaveMonsterInfoOrBuilder(
        int index) {
      return curWaveMonsterInfo_.get(index);
    }

    public static final int PETSREMAINHP_FIELD_NUMBER = 4;
    private static final class PetsRemainHpDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, protocol.Battle.BattleRemainPet> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, protocol.Battle.BattleRemainPet>newDefaultInstance(
                  protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionBuildingPlayerInfo_PetsRemainHpEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  protocol.Battle.BattleRemainPet.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, protocol.Battle.BattleRemainPet> petsRemainHp_;
    private com.google.protobuf.MapField<java.lang.String, protocol.Battle.BattleRemainPet>
    internalGetPetsRemainHp() {
      if (petsRemainHp_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            PetsRemainHpDefaultEntryHolder.defaultEntry);
      }
      return petsRemainHp_;
    }

    public int getPetsRemainHpCount() {
      return internalGetPetsRemainHp().getMap().size();
    }
    /**
     * <pre>
     *备战宠物剩余血量
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
     */

    public boolean containsPetsRemainHp(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetPetsRemainHp().getMap().containsKey(key);
    }
    /**
     * Use {@link #getPetsRemainHpMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> getPetsRemainHp() {
      return getPetsRemainHpMap();
    }
    /**
     * <pre>
     *备战宠物剩余血量
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
     */

    public java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> getPetsRemainHpMap() {
      return internalGetPetsRemainHp().getMap();
    }
    /**
     * <pre>
     *备战宠物剩余血量
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
     */

    public protocol.Battle.BattleRemainPet getPetsRemainHpOrDefault(
        java.lang.String key,
        protocol.Battle.BattleRemainPet defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> map =
          internalGetPetsRemainHp().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *备战宠物剩余血量
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
     */

    public protocol.Battle.BattleRemainPet getPetsRemainHpOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> map =
          internalGetPetsRemainHp().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int MONSTERREMAINHP_FIELD_NUMBER = 5;
    private static final class MonsterRemainHpDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, protocol.Battle.BattleRemainPet> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, protocol.Battle.BattleRemainPet>newDefaultInstance(
                  protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionBuildingPlayerInfo_MonsterRemainHpEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  protocol.Battle.BattleRemainPet.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, protocol.Battle.BattleRemainPet> monsterRemainHp_;
    private com.google.protobuf.MapField<java.lang.String, protocol.Battle.BattleRemainPet>
    internalGetMonsterRemainHp() {
      if (monsterRemainHp_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MonsterRemainHpDefaultEntryHolder.defaultEntry);
      }
      return monsterRemainHp_;
    }

    public int getMonsterRemainHpCount() {
      return internalGetMonsterRemainHp().getMap().size();
    }
    /**
     * <pre>
     *当前关卡怪物
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
     */

    public boolean containsMonsterRemainHp(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMonsterRemainHp().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMonsterRemainHpMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> getMonsterRemainHp() {
      return getMonsterRemainHpMap();
    }
    /**
     * <pre>
     *当前关卡怪物
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
     */

    public java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> getMonsterRemainHpMap() {
      return internalGetMonsterRemainHp().getMap();
    }
    /**
     * <pre>
     *当前关卡怪物
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
     */

    public protocol.Battle.BattleRemainPet getMonsterRemainHpOrDefault(
        java.lang.String key,
        protocol.Battle.BattleRemainPet defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> map =
          internalGetMonsterRemainHp().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *当前关卡怪物
     * </pre>
     *
     * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
     */

    public protocol.Battle.BattleRemainPet getMonsterRemainHpOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> map =
          internalGetMonsterRemainHp().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (buildingId_ != 0) {
        output.writeInt32(1, buildingId_);
      }
      if (curWave_ != 0) {
        output.writeInt32(2, curWave_);
      }
      for (int i = 0; i < curWaveMonsterInfo_.size(); i++) {
        output.writeMessage(3, curWaveMonsterInfo_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetPetsRemainHp(),
          PetsRemainHpDefaultEntryHolder.defaultEntry,
          4);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMonsterRemainHp(),
          MonsterRemainHpDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (buildingId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, buildingId_);
      }
      if (curWave_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, curWave_);
      }
      for (int i = 0; i < curWaveMonsterInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, curWaveMonsterInfo_.get(i));
      }
      for (java.util.Map.Entry<java.lang.String, protocol.Battle.BattleRemainPet> entry
           : internalGetPetsRemainHp().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, protocol.Battle.BattleRemainPet>
        petsRemainHp__ = PetsRemainHpDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, petsRemainHp__);
      }
      for (java.util.Map.Entry<java.lang.String, protocol.Battle.BattleRemainPet> entry
           : internalGetMonsterRemainHp().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, protocol.Battle.BattleRemainPet>
        monsterRemainHp__ = MonsterRemainHpDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, monsterRemainHp__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo)) {
        return super.equals(obj);
      }
      protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo other = (protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo) obj;

      boolean result = true;
      result = result && (getBuildingId()
          == other.getBuildingId());
      result = result && (getCurWave()
          == other.getCurWave());
      result = result && getCurWaveMonsterInfoList()
          .equals(other.getCurWaveMonsterInfoList());
      result = result && internalGetPetsRemainHp().equals(
          other.internalGetPetsRemainHp());
      result = result && internalGetMonsterRemainHp().equals(
          other.internalGetMonsterRemainHp());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BUILDINGID_FIELD_NUMBER;
      hash = (53 * hash) + getBuildingId();
      hash = (37 * hash) + CURWAVE_FIELD_NUMBER;
      hash = (53 * hash) + getCurWave();
      if (getCurWaveMonsterInfoCount() > 0) {
        hash = (37 * hash) + CURWAVEMONSTERINFO_FIELD_NUMBER;
        hash = (53 * hash) + getCurWaveMonsterInfoList().hashCode();
      }
      if (!internalGetPetsRemainHp().getMap().isEmpty()) {
        hash = (37 * hash) + PETSREMAINHP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetPetsRemainHp().hashCode();
      }
      if (!internalGetMonsterRemainHp().getMap().isEmpty()) {
        hash = (37 * hash) + MONSTERREMAINHP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMonsterRemainHp().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DB_ForeignInvasionBuildingPlayerInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DB_ForeignInvasionBuildingPlayerInfo)
        protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionBuildingPlayerInfo_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetPetsRemainHp();
          case 5:
            return internalGetMonsterRemainHp();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 4:
            return internalGetMutablePetsRemainHp();
          case 5:
            return internalGetMutableMonsterRemainHp();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionBuildingPlayerInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo.class, protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo.Builder.class);
      }

      // Construct using protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getCurWaveMonsterInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        buildingId_ = 0;

        curWave_ = 0;

        if (curWaveMonsterInfoBuilder_ == null) {
          curWaveMonsterInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          curWaveMonsterInfoBuilder_.clear();
        }
        internalGetMutablePetsRemainHp().clear();
        internalGetMutableMonsterRemainHp().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ForeignInvasionDB.internal_static_DB_ForeignInvasionBuildingPlayerInfo_descriptor;
      }

      public protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo getDefaultInstanceForType() {
        return protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo.getDefaultInstance();
      }

      public protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo build() {
        protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo buildPartial() {
        protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo result = new protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.buildingId_ = buildingId_;
        result.curWave_ = curWave_;
        if (curWaveMonsterInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            curWaveMonsterInfo_ = java.util.Collections.unmodifiableList(curWaveMonsterInfo_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.curWaveMonsterInfo_ = curWaveMonsterInfo_;
        } else {
          result.curWaveMonsterInfo_ = curWaveMonsterInfoBuilder_.build();
        }
        result.petsRemainHp_ = internalGetPetsRemainHp();
        result.petsRemainHp_.makeImmutable();
        result.monsterRemainHp_ = internalGetMonsterRemainHp();
        result.monsterRemainHp_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo) {
          return mergeFrom((protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo other) {
        if (other == protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo.getDefaultInstance()) return this;
        if (other.getBuildingId() != 0) {
          setBuildingId(other.getBuildingId());
        }
        if (other.getCurWave() != 0) {
          setCurWave(other.getCurWave());
        }
        if (curWaveMonsterInfoBuilder_ == null) {
          if (!other.curWaveMonsterInfo_.isEmpty()) {
            if (curWaveMonsterInfo_.isEmpty()) {
              curWaveMonsterInfo_ = other.curWaveMonsterInfo_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureCurWaveMonsterInfoIsMutable();
              curWaveMonsterInfo_.addAll(other.curWaveMonsterInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.curWaveMonsterInfo_.isEmpty()) {
            if (curWaveMonsterInfoBuilder_.isEmpty()) {
              curWaveMonsterInfoBuilder_.dispose();
              curWaveMonsterInfoBuilder_ = null;
              curWaveMonsterInfo_ = other.curWaveMonsterInfo_;
              bitField0_ = (bitField0_ & ~0x00000004);
              curWaveMonsterInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getCurWaveMonsterInfoFieldBuilder() : null;
            } else {
              curWaveMonsterInfoBuilder_.addAllMessages(other.curWaveMonsterInfo_);
            }
          }
        }
        internalGetMutablePetsRemainHp().mergeFrom(
            other.internalGetPetsRemainHp());
        internalGetMutableMonsterRemainHp().mergeFrom(
            other.internalGetMonsterRemainHp());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int buildingId_ ;
      /**
       * <pre>
       *建筑Id
       * </pre>
       *
       * <code>int32 buildingId = 1;</code>
       */
      public int getBuildingId() {
        return buildingId_;
      }
      /**
       * <pre>
       *建筑Id
       * </pre>
       *
       * <code>int32 buildingId = 1;</code>
       */
      public Builder setBuildingId(int value) {
        
        buildingId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *建筑Id
       * </pre>
       *
       * <code>int32 buildingId = 1;</code>
       */
      public Builder clearBuildingId() {
        
        buildingId_ = 0;
        onChanged();
        return this;
      }

      private int curWave_ ;
      /**
       * <pre>
       *当前波次
       * </pre>
       *
       * <code>int32 curWave = 2;</code>
       */
      public int getCurWave() {
        return curWave_;
      }
      /**
       * <pre>
       *当前波次
       * </pre>
       *
       * <code>int32 curWave = 2;</code>
       */
      public Builder setCurWave(int value) {
        
        curWave_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前波次
       * </pre>
       *
       * <code>int32 curWave = 2;</code>
       */
      public Builder clearCurWave() {
        
        curWave_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<protocol.Battle.BattlePetData> curWaveMonsterInfo_ =
        java.util.Collections.emptyList();
      private void ensureCurWaveMonsterInfoIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          curWaveMonsterInfo_ = new java.util.ArrayList<protocol.Battle.BattlePetData>(curWaveMonsterInfo_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Battle.BattlePetData, protocol.Battle.BattlePetData.Builder, protocol.Battle.BattlePetDataOrBuilder> curWaveMonsterInfoBuilder_;

      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public java.util.List<protocol.Battle.BattlePetData> getCurWaveMonsterInfoList() {
        if (curWaveMonsterInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(curWaveMonsterInfo_);
        } else {
          return curWaveMonsterInfoBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public int getCurWaveMonsterInfoCount() {
        if (curWaveMonsterInfoBuilder_ == null) {
          return curWaveMonsterInfo_.size();
        } else {
          return curWaveMonsterInfoBuilder_.getCount();
        }
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public protocol.Battle.BattlePetData getCurWaveMonsterInfo(int index) {
        if (curWaveMonsterInfoBuilder_ == null) {
          return curWaveMonsterInfo_.get(index);
        } else {
          return curWaveMonsterInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public Builder setCurWaveMonsterInfo(
          int index, protocol.Battle.BattlePetData value) {
        if (curWaveMonsterInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurWaveMonsterInfoIsMutable();
          curWaveMonsterInfo_.set(index, value);
          onChanged();
        } else {
          curWaveMonsterInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public Builder setCurWaveMonsterInfo(
          int index, protocol.Battle.BattlePetData.Builder builderForValue) {
        if (curWaveMonsterInfoBuilder_ == null) {
          ensureCurWaveMonsterInfoIsMutable();
          curWaveMonsterInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          curWaveMonsterInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public Builder addCurWaveMonsterInfo(protocol.Battle.BattlePetData value) {
        if (curWaveMonsterInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurWaveMonsterInfoIsMutable();
          curWaveMonsterInfo_.add(value);
          onChanged();
        } else {
          curWaveMonsterInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public Builder addCurWaveMonsterInfo(
          int index, protocol.Battle.BattlePetData value) {
        if (curWaveMonsterInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureCurWaveMonsterInfoIsMutable();
          curWaveMonsterInfo_.add(index, value);
          onChanged();
        } else {
          curWaveMonsterInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public Builder addCurWaveMonsterInfo(
          protocol.Battle.BattlePetData.Builder builderForValue) {
        if (curWaveMonsterInfoBuilder_ == null) {
          ensureCurWaveMonsterInfoIsMutable();
          curWaveMonsterInfo_.add(builderForValue.build());
          onChanged();
        } else {
          curWaveMonsterInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public Builder addCurWaveMonsterInfo(
          int index, protocol.Battle.BattlePetData.Builder builderForValue) {
        if (curWaveMonsterInfoBuilder_ == null) {
          ensureCurWaveMonsterInfoIsMutable();
          curWaveMonsterInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          curWaveMonsterInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public Builder addAllCurWaveMonsterInfo(
          java.lang.Iterable<? extends protocol.Battle.BattlePetData> values) {
        if (curWaveMonsterInfoBuilder_ == null) {
          ensureCurWaveMonsterInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, curWaveMonsterInfo_);
          onChanged();
        } else {
          curWaveMonsterInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public Builder clearCurWaveMonsterInfo() {
        if (curWaveMonsterInfoBuilder_ == null) {
          curWaveMonsterInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          curWaveMonsterInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public Builder removeCurWaveMonsterInfo(int index) {
        if (curWaveMonsterInfoBuilder_ == null) {
          ensureCurWaveMonsterInfoIsMutable();
          curWaveMonsterInfo_.remove(index);
          onChanged();
        } else {
          curWaveMonsterInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public protocol.Battle.BattlePetData.Builder getCurWaveMonsterInfoBuilder(
          int index) {
        return getCurWaveMonsterInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public protocol.Battle.BattlePetDataOrBuilder getCurWaveMonsterInfoOrBuilder(
          int index) {
        if (curWaveMonsterInfoBuilder_ == null) {
          return curWaveMonsterInfo_.get(index);  } else {
          return curWaveMonsterInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public java.util.List<? extends protocol.Battle.BattlePetDataOrBuilder> 
           getCurWaveMonsterInfoOrBuilderList() {
        if (curWaveMonsterInfoBuilder_ != null) {
          return curWaveMonsterInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(curWaveMonsterInfo_);
        }
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public protocol.Battle.BattlePetData.Builder addCurWaveMonsterInfoBuilder() {
        return getCurWaveMonsterInfoFieldBuilder().addBuilder(
            protocol.Battle.BattlePetData.getDefaultInstance());
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public protocol.Battle.BattlePetData.Builder addCurWaveMonsterInfoBuilder(
          int index) {
        return getCurWaveMonsterInfoFieldBuilder().addBuilder(
            index, protocol.Battle.BattlePetData.getDefaultInstance());
      }
      /**
       * <pre>
       *当前波次怪物阵容
       * </pre>
       *
       * <code>repeated .BattlePetData curWaveMonsterInfo = 3;</code>
       */
      public java.util.List<protocol.Battle.BattlePetData.Builder> 
           getCurWaveMonsterInfoBuilderList() {
        return getCurWaveMonsterInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Battle.BattlePetData, protocol.Battle.BattlePetData.Builder, protocol.Battle.BattlePetDataOrBuilder> 
          getCurWaveMonsterInfoFieldBuilder() {
        if (curWaveMonsterInfoBuilder_ == null) {
          curWaveMonsterInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.Battle.BattlePetData, protocol.Battle.BattlePetData.Builder, protocol.Battle.BattlePetDataOrBuilder>(
                  curWaveMonsterInfo_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          curWaveMonsterInfo_ = null;
        }
        return curWaveMonsterInfoBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.String, protocol.Battle.BattleRemainPet> petsRemainHp_;
      private com.google.protobuf.MapField<java.lang.String, protocol.Battle.BattleRemainPet>
      internalGetPetsRemainHp() {
        if (petsRemainHp_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              PetsRemainHpDefaultEntryHolder.defaultEntry);
        }
        return petsRemainHp_;
      }
      private com.google.protobuf.MapField<java.lang.String, protocol.Battle.BattleRemainPet>
      internalGetMutablePetsRemainHp() {
        onChanged();;
        if (petsRemainHp_ == null) {
          petsRemainHp_ = com.google.protobuf.MapField.newMapField(
              PetsRemainHpDefaultEntryHolder.defaultEntry);
        }
        if (!petsRemainHp_.isMutable()) {
          petsRemainHp_ = petsRemainHp_.copy();
        }
        return petsRemainHp_;
      }

      public int getPetsRemainHpCount() {
        return internalGetPetsRemainHp().getMap().size();
      }
      /**
       * <pre>
       *备战宠物剩余血量
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
       */

      public boolean containsPetsRemainHp(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetPetsRemainHp().getMap().containsKey(key);
      }
      /**
       * Use {@link #getPetsRemainHpMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> getPetsRemainHp() {
        return getPetsRemainHpMap();
      }
      /**
       * <pre>
       *备战宠物剩余血量
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
       */

      public java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> getPetsRemainHpMap() {
        return internalGetPetsRemainHp().getMap();
      }
      /**
       * <pre>
       *备战宠物剩余血量
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
       */

      public protocol.Battle.BattleRemainPet getPetsRemainHpOrDefault(
          java.lang.String key,
          protocol.Battle.BattleRemainPet defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> map =
            internalGetPetsRemainHp().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *备战宠物剩余血量
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
       */

      public protocol.Battle.BattleRemainPet getPetsRemainHpOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> map =
            internalGetPetsRemainHp().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearPetsRemainHp() {
        internalGetMutablePetsRemainHp().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *备战宠物剩余血量
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
       */

      public Builder removePetsRemainHp(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutablePetsRemainHp().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet>
      getMutablePetsRemainHp() {
        return internalGetMutablePetsRemainHp().getMutableMap();
      }
      /**
       * <pre>
       *备战宠物剩余血量
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
       */
      public Builder putPetsRemainHp(
          java.lang.String key,
          protocol.Battle.BattleRemainPet value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutablePetsRemainHp().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *备战宠物剩余血量
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; petsRemainHp = 4;</code>
       */

      public Builder putAllPetsRemainHp(
          java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> values) {
        internalGetMutablePetsRemainHp().getMutableMap()
            .putAll(values);
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, protocol.Battle.BattleRemainPet> monsterRemainHp_;
      private com.google.protobuf.MapField<java.lang.String, protocol.Battle.BattleRemainPet>
      internalGetMonsterRemainHp() {
        if (monsterRemainHp_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MonsterRemainHpDefaultEntryHolder.defaultEntry);
        }
        return monsterRemainHp_;
      }
      private com.google.protobuf.MapField<java.lang.String, protocol.Battle.BattleRemainPet>
      internalGetMutableMonsterRemainHp() {
        onChanged();;
        if (monsterRemainHp_ == null) {
          monsterRemainHp_ = com.google.protobuf.MapField.newMapField(
              MonsterRemainHpDefaultEntryHolder.defaultEntry);
        }
        if (!monsterRemainHp_.isMutable()) {
          monsterRemainHp_ = monsterRemainHp_.copy();
        }
        return monsterRemainHp_;
      }

      public int getMonsterRemainHpCount() {
        return internalGetMonsterRemainHp().getMap().size();
      }
      /**
       * <pre>
       *当前关卡怪物
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
       */

      public boolean containsMonsterRemainHp(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMonsterRemainHp().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMonsterRemainHpMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> getMonsterRemainHp() {
        return getMonsterRemainHpMap();
      }
      /**
       * <pre>
       *当前关卡怪物
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
       */

      public java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> getMonsterRemainHpMap() {
        return internalGetMonsterRemainHp().getMap();
      }
      /**
       * <pre>
       *当前关卡怪物
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
       */

      public protocol.Battle.BattleRemainPet getMonsterRemainHpOrDefault(
          java.lang.String key,
          protocol.Battle.BattleRemainPet defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> map =
            internalGetMonsterRemainHp().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *当前关卡怪物
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
       */

      public protocol.Battle.BattleRemainPet getMonsterRemainHpOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> map =
            internalGetMonsterRemainHp().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMonsterRemainHp() {
        internalGetMutableMonsterRemainHp().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *当前关卡怪物
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
       */

      public Builder removeMonsterRemainHp(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMonsterRemainHp().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet>
      getMutableMonsterRemainHp() {
        return internalGetMutableMonsterRemainHp().getMutableMap();
      }
      /**
       * <pre>
       *当前关卡怪物
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
       */
      public Builder putMonsterRemainHp(
          java.lang.String key,
          protocol.Battle.BattleRemainPet value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMonsterRemainHp().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *当前关卡怪物
       * </pre>
       *
       * <code>map&lt;string, .BattleRemainPet&gt; monsterRemainHp = 5;</code>
       */

      public Builder putAllMonsterRemainHp(
          java.util.Map<java.lang.String, protocol.Battle.BattleRemainPet> values) {
        internalGetMutableMonsterRemainHp().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DB_ForeignInvasionBuildingPlayerInfo)
    }

    // @@protoc_insertion_point(class_scope:DB_ForeignInvasionBuildingPlayerInfo)
    private static final protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo();
    }

    public static protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DB_ForeignInvasionBuildingPlayerInfo>
        PARSER = new com.google.protobuf.AbstractParser<DB_ForeignInvasionBuildingPlayerInfo>() {
      public DB_ForeignInvasionBuildingPlayerInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DB_ForeignInvasionBuildingPlayerInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DB_ForeignInvasionBuildingPlayerInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DB_ForeignInvasionBuildingPlayerInfo> getParserForType() {
      return PARSER;
    }

    public protocol.ForeignInvasionDB.DB_ForeignInvasionBuildingPlayerInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_ForeignInvasionPlayerInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_ForeignInvasionPlayerInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_ForeignInvasionPlayerInfo_BuildingsInfoEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_ForeignInvasionPlayerInfo_BuildingsInfoEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_ForeignInvasionBuildingPlayerInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_ForeignInvasionBuildingPlayerInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_ForeignInvasionBuildingPlayerInfo_PetsRemainHpEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_ForeignInvasionBuildingPlayerInfo_PetsRemainHpEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_ForeignInvasionBuildingPlayerInfo_MonsterRemainHpEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_ForeignInvasionBuildingPlayerInfo_MonsterRemainHpEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027ForeignInvasionDB.proto\032\014Battle.proto\"" +
      "\304\001\n\034DB_ForeignInvasionPlayerInfo\022G\n\rbuil" +
      "dingsInfo\030\001 \003(\01320.DB_ForeignInvasionPlay" +
      "erInfo.BuildingsInfoEntry\032[\n\022BuildingsIn" +
      "foEntry\022\013\n\003key\030\001 \001(\005\0224\n\005value\030\002 \001(\0132%.DB" +
      "_ForeignInvasionBuildingPlayerInfo:\0028\001\"\254" +
      "\003\n$DB_ForeignInvasionBuildingPlayerInfo\022" +
      "\022\n\nbuildingId\030\001 \001(\005\022\017\n\007curWave\030\002 \001(\005\022*\n\022" +
      "curWaveMonsterInfo\030\003 \003(\0132\016.BattlePetData" +
      "\022M\n\014petsRemainHp\030\004 \003(\01327.DB_ForeignInvas",
      "ionBuildingPlayerInfo.PetsRemainHpEntry\022" +
      "S\n\017monsterRemainHp\030\005 \003(\0132:.DB_ForeignInv" +
      "asionBuildingPlayerInfo.MonsterRemainHpE" +
      "ntry\032E\n\021PetsRemainHpEntry\022\013\n\003key\030\001 \001(\t\022\037" +
      "\n\005value\030\002 \001(\0132\020.BattleRemainPet:\0028\001\032H\n\024M" +
      "onsterRemainHpEntry\022\013\n\003key\030\001 \001(\t\022\037\n\005valu" +
      "e\030\002 \001(\0132\020.BattleRemainPet:\0028\001B\033\n\010protoco" +
      "l\252\002\016ETHotfix.Protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.Battle.getDescriptor(),
        }, assigner);
    internal_static_DB_ForeignInvasionPlayerInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DB_ForeignInvasionPlayerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_ForeignInvasionPlayerInfo_descriptor,
        new java.lang.String[] { "BuildingsInfo", });
    internal_static_DB_ForeignInvasionPlayerInfo_BuildingsInfoEntry_descriptor =
      internal_static_DB_ForeignInvasionPlayerInfo_descriptor.getNestedTypes().get(0);
    internal_static_DB_ForeignInvasionPlayerInfo_BuildingsInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_ForeignInvasionPlayerInfo_BuildingsInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_DB_ForeignInvasionBuildingPlayerInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DB_ForeignInvasionBuildingPlayerInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_ForeignInvasionBuildingPlayerInfo_descriptor,
        new java.lang.String[] { "BuildingId", "CurWave", "CurWaveMonsterInfo", "PetsRemainHp", "MonsterRemainHp", });
    internal_static_DB_ForeignInvasionBuildingPlayerInfo_PetsRemainHpEntry_descriptor =
      internal_static_DB_ForeignInvasionBuildingPlayerInfo_descriptor.getNestedTypes().get(0);
    internal_static_DB_ForeignInvasionBuildingPlayerInfo_PetsRemainHpEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_ForeignInvasionBuildingPlayerInfo_PetsRemainHpEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_DB_ForeignInvasionBuildingPlayerInfo_MonsterRemainHpEntry_descriptor =
      internal_static_DB_ForeignInvasionBuildingPlayerInfo_descriptor.getNestedTypes().get(1);
    internal_static_DB_ForeignInvasionBuildingPlayerInfo_MonsterRemainHpEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_ForeignInvasionBuildingPlayerInfo_MonsterRemainHpEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    protocol.Battle.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
