// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MailDB.proto

package protocol;

public final class MailDB {
  private MailDB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DB_MailBoxOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DB_MailBox)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
     */
    int getMailsCount();
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
     */
    boolean containsMails(
        java.lang.String key);
    /**
     * Use {@link #getMailsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo>
    getMails();
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
     */
    java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo>
    getMailsMap();
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
     */

    protocol.MailDB.DB_MailInfo getMailsOrDefault(
        java.lang.String key,
        protocol.MailDB.DB_MailInfo defaultValue);
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
     */

    protocol.MailDB.DB_MailInfo getMailsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code DB_MailBox}
   */
  public  static final class DB_MailBox extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DB_MailBox)
      DB_MailBoxOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DB_MailBox.newBuilder() to construct.
    private DB_MailBox(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DB_MailBox() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DB_MailBox(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                mails_ = com.google.protobuf.MapField.newMapField(
                    MailsDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.String, protocol.MailDB.DB_MailInfo>
              mails__ = input.readMessage(
                  MailsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              mails_.getMutableMap().put(
                  mails__.getKey(), mails__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.MailDB.internal_static_DB_MailBox_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetMails();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.MailDB.internal_static_DB_MailBox_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.MailDB.DB_MailBox.class, protocol.MailDB.DB_MailBox.Builder.class);
    }

    public static final int MAILS_FIELD_NUMBER = 2;
    private static final class MailsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, protocol.MailDB.DB_MailInfo> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, protocol.MailDB.DB_MailInfo>newDefaultInstance(
                  protocol.MailDB.internal_static_DB_MailBox_MailsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  protocol.MailDB.DB_MailInfo.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.String, protocol.MailDB.DB_MailInfo> mails_;
    private com.google.protobuf.MapField<java.lang.String, protocol.MailDB.DB_MailInfo>
    internalGetMails() {
      if (mails_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            MailsDefaultEntryHolder.defaultEntry);
      }
      return mails_;
    }

    public int getMailsCount() {
      return internalGetMails().getMap().size();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
     */

    public boolean containsMails(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetMails().getMap().containsKey(key);
    }
    /**
     * Use {@link #getMailsMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo> getMails() {
      return getMailsMap();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
     */

    public java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo> getMailsMap() {
      return internalGetMails().getMap();
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
     */

    public protocol.MailDB.DB_MailInfo getMailsOrDefault(
        java.lang.String key,
        protocol.MailDB.DB_MailInfo defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo> map =
          internalGetMails().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
     */

    public protocol.MailDB.DB_MailInfo getMailsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo> map =
          internalGetMails().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetMails(),
          MailsDefaultEntryHolder.defaultEntry,
          2);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, protocol.MailDB.DB_MailInfo> entry
           : internalGetMails().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, protocol.MailDB.DB_MailInfo>
        mails__ = MailsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, mails__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.MailDB.DB_MailBox)) {
        return super.equals(obj);
      }
      protocol.MailDB.DB_MailBox other = (protocol.MailDB.DB_MailBox) obj;

      boolean result = true;
      result = result && internalGetMails().equals(
          other.internalGetMails());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetMails().getMap().isEmpty()) {
        hash = (37 * hash) + MAILS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetMails().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.MailDB.DB_MailBox parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MailDB.DB_MailBox parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MailDB.DB_MailBox parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MailDB.DB_MailBox parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MailDB.DB_MailBox parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MailDB.DB_MailBox parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MailDB.DB_MailBox parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.MailDB.DB_MailBox parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.MailDB.DB_MailBox parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.MailDB.DB_MailBox parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.MailDB.DB_MailBox parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.MailDB.DB_MailBox parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.MailDB.DB_MailBox prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DB_MailBox}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DB_MailBox)
        protocol.MailDB.DB_MailBoxOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.MailDB.internal_static_DB_MailBox_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMails();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableMails();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.MailDB.internal_static_DB_MailBox_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.MailDB.DB_MailBox.class, protocol.MailDB.DB_MailBox.Builder.class);
      }

      // Construct using protocol.MailDB.DB_MailBox.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableMails().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.MailDB.internal_static_DB_MailBox_descriptor;
      }

      public protocol.MailDB.DB_MailBox getDefaultInstanceForType() {
        return protocol.MailDB.DB_MailBox.getDefaultInstance();
      }

      public protocol.MailDB.DB_MailBox build() {
        protocol.MailDB.DB_MailBox result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.MailDB.DB_MailBox buildPartial() {
        protocol.MailDB.DB_MailBox result = new protocol.MailDB.DB_MailBox(this);
        int from_bitField0_ = bitField0_;
        result.mails_ = internalGetMails();
        result.mails_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.MailDB.DB_MailBox) {
          return mergeFrom((protocol.MailDB.DB_MailBox)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.MailDB.DB_MailBox other) {
        if (other == protocol.MailDB.DB_MailBox.getDefaultInstance()) return this;
        internalGetMutableMails().mergeFrom(
            other.internalGetMails());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.MailDB.DB_MailBox parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.MailDB.DB_MailBox) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, protocol.MailDB.DB_MailInfo> mails_;
      private com.google.protobuf.MapField<java.lang.String, protocol.MailDB.DB_MailInfo>
      internalGetMails() {
        if (mails_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              MailsDefaultEntryHolder.defaultEntry);
        }
        return mails_;
      }
      private com.google.protobuf.MapField<java.lang.String, protocol.MailDB.DB_MailInfo>
      internalGetMutableMails() {
        onChanged();;
        if (mails_ == null) {
          mails_ = com.google.protobuf.MapField.newMapField(
              MailsDefaultEntryHolder.defaultEntry);
        }
        if (!mails_.isMutable()) {
          mails_ = mails_.copy();
        }
        return mails_;
      }

      public int getMailsCount() {
        return internalGetMails().getMap().size();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
       */

      public boolean containsMails(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetMails().getMap().containsKey(key);
      }
      /**
       * Use {@link #getMailsMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo> getMails() {
        return getMailsMap();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
       */

      public java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo> getMailsMap() {
        return internalGetMails().getMap();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
       */

      public protocol.MailDB.DB_MailInfo getMailsOrDefault(
          java.lang.String key,
          protocol.MailDB.DB_MailInfo defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo> map =
            internalGetMails().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
       */

      public protocol.MailDB.DB_MailInfo getMailsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo> map =
            internalGetMails().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearMails() {
        internalGetMutableMails().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
       */

      public Builder removeMails(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMails().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo>
      getMutableMails() {
        return internalGetMutableMails().getMutableMap();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
       */
      public Builder putMails(
          java.lang.String key,
          protocol.MailDB.DB_MailInfo value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableMails().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>map&lt;string, .DB_MailInfo&gt; mails = 2;</code>
       */

      public Builder putAllMails(
          java.util.Map<java.lang.String, protocol.MailDB.DB_MailInfo> values) {
        internalGetMutableMails().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DB_MailBox)
    }

    // @@protoc_insertion_point(class_scope:DB_MailBox)
    private static final protocol.MailDB.DB_MailBox DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.MailDB.DB_MailBox();
    }

    public static protocol.MailDB.DB_MailBox getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DB_MailBox>
        PARSER = new com.google.protobuf.AbstractParser<DB_MailBox>() {
      public DB_MailBox parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DB_MailBox(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DB_MailBox> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DB_MailBox> getParserForType() {
      return PARSER;
    }

    public protocol.MailDB.DB_MailBox getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DB_MailInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DB_MailInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mailIdx = 1;</code>
     */
    java.lang.String getMailIdx();
    /**
     * <code>string mailIdx = 1;</code>
     */
    com.google.protobuf.ByteString
        getMailIdxBytes();

    /**
     * <code>int64 mailTemplateId = 3;</code>
     */
    long getMailTemplateId();

    /**
     * <code>repeated .Reward rewards = 4;</code>
     */
    java.util.List<protocol.Common.Reward> 
        getRewardsList();
    /**
     * <code>repeated .Reward rewards = 4;</code>
     */
    protocol.Common.Reward getRewards(int index);
    /**
     * <code>repeated .Reward rewards = 4;</code>
     */
    int getRewardsCount();
    /**
     * <code>repeated .Reward rewards = 4;</code>
     */
    java.util.List<? extends protocol.Common.RewardOrBuilder> 
        getRewardsOrBuilderList();
    /**
     * <code>repeated .Reward rewards = 4;</code>
     */
    protocol.Common.RewardOrBuilder getRewardsOrBuilder(
        int index);

    /**
     * <code>.MailStatusEnum mailStatus = 5;</code>
     */
    int getMailStatusValue();
    /**
     * <code>.MailStatusEnum mailStatus = 5;</code>
     */
    protocol.Mail.MailStatusEnum getMailStatus();

    /**
     * <code>int64 createTime = 6;</code>
     */
    long getCreateTime();

    /**
     * <code>int64 expireTime = 7;</code>
     */
    long getExpireTime();

    /**
     * <code>repeated string param = 8;</code>
     */
    java.util.List<java.lang.String>
        getParamList();
    /**
     * <code>repeated string param = 8;</code>
     */
    int getParamCount();
    /**
     * <code>repeated string param = 8;</code>
     */
    java.lang.String getParam(int index);
    /**
     * <code>repeated string param = 8;</code>
     */
    com.google.protobuf.ByteString
        getParamBytes(int index);
  }
  /**
   * Protobuf type {@code DB_MailInfo}
   */
  public  static final class DB_MailInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DB_MailInfo)
      DB_MailInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DB_MailInfo.newBuilder() to construct.
    private DB_MailInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DB_MailInfo() {
      mailIdx_ = "";
      mailTemplateId_ = 0L;
      rewards_ = java.util.Collections.emptyList();
      mailStatus_ = 0;
      createTime_ = 0L;
      expireTime_ = 0L;
      param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DB_MailInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              mailIdx_ = s;
              break;
            }
            case 24: {

              mailTemplateId_ = input.readInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                rewards_ = new java.util.ArrayList<protocol.Common.Reward>();
                mutable_bitField0_ |= 0x00000004;
              }
              rewards_.add(
                  input.readMessage(protocol.Common.Reward.parser(), extensionRegistry));
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              mailStatus_ = rawValue;
              break;
            }
            case 48: {

              createTime_ = input.readInt64();
              break;
            }
            case 56: {

              expireTime_ = input.readInt64();
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                param_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000040;
              }
              param_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          rewards_ = java.util.Collections.unmodifiableList(rewards_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          param_ = param_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.MailDB.internal_static_DB_MailInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.MailDB.internal_static_DB_MailInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.MailDB.DB_MailInfo.class, protocol.MailDB.DB_MailInfo.Builder.class);
    }

    private int bitField0_;
    public static final int MAILIDX_FIELD_NUMBER = 1;
    private volatile java.lang.Object mailIdx_;
    /**
     * <code>string mailIdx = 1;</code>
     */
    public java.lang.String getMailIdx() {
      java.lang.Object ref = mailIdx_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        mailIdx_ = s;
        return s;
      }
    }
    /**
     * <code>string mailIdx = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMailIdxBytes() {
      java.lang.Object ref = mailIdx_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mailIdx_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MAILTEMPLATEID_FIELD_NUMBER = 3;
    private long mailTemplateId_;
    /**
     * <code>int64 mailTemplateId = 3;</code>
     */
    public long getMailTemplateId() {
      return mailTemplateId_;
    }

    public static final int REWARDS_FIELD_NUMBER = 4;
    private java.util.List<protocol.Common.Reward> rewards_;
    /**
     * <code>repeated .Reward rewards = 4;</code>
     */
    public java.util.List<protocol.Common.Reward> getRewardsList() {
      return rewards_;
    }
    /**
     * <code>repeated .Reward rewards = 4;</code>
     */
    public java.util.List<? extends protocol.Common.RewardOrBuilder> 
        getRewardsOrBuilderList() {
      return rewards_;
    }
    /**
     * <code>repeated .Reward rewards = 4;</code>
     */
    public int getRewardsCount() {
      return rewards_.size();
    }
    /**
     * <code>repeated .Reward rewards = 4;</code>
     */
    public protocol.Common.Reward getRewards(int index) {
      return rewards_.get(index);
    }
    /**
     * <code>repeated .Reward rewards = 4;</code>
     */
    public protocol.Common.RewardOrBuilder getRewardsOrBuilder(
        int index) {
      return rewards_.get(index);
    }

    public static final int MAILSTATUS_FIELD_NUMBER = 5;
    private int mailStatus_;
    /**
     * <code>.MailStatusEnum mailStatus = 5;</code>
     */
    public int getMailStatusValue() {
      return mailStatus_;
    }
    /**
     * <code>.MailStatusEnum mailStatus = 5;</code>
     */
    public protocol.Mail.MailStatusEnum getMailStatus() {
      protocol.Mail.MailStatusEnum result = protocol.Mail.MailStatusEnum.valueOf(mailStatus_);
      return result == null ? protocol.Mail.MailStatusEnum.UNRECOGNIZED : result;
    }

    public static final int CREATETIME_FIELD_NUMBER = 6;
    private long createTime_;
    /**
     * <code>int64 createTime = 6;</code>
     */
    public long getCreateTime() {
      return createTime_;
    }

    public static final int EXPIRETIME_FIELD_NUMBER = 7;
    private long expireTime_;
    /**
     * <code>int64 expireTime = 7;</code>
     */
    public long getExpireTime() {
      return expireTime_;
    }

    public static final int PARAM_FIELD_NUMBER = 8;
    private com.google.protobuf.LazyStringList param_;
    /**
     * <code>repeated string param = 8;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getParamList() {
      return param_;
    }
    /**
     * <code>repeated string param = 8;</code>
     */
    public int getParamCount() {
      return param_.size();
    }
    /**
     * <code>repeated string param = 8;</code>
     */
    public java.lang.String getParam(int index) {
      return param_.get(index);
    }
    /**
     * <code>repeated string param = 8;</code>
     */
    public com.google.protobuf.ByteString
        getParamBytes(int index) {
      return param_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMailIdxBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mailIdx_);
      }
      if (mailTemplateId_ != 0L) {
        output.writeInt64(3, mailTemplateId_);
      }
      for (int i = 0; i < rewards_.size(); i++) {
        output.writeMessage(4, rewards_.get(i));
      }
      if (mailStatus_ != protocol.Mail.MailStatusEnum.MSE_NoAttachmentUnread.getNumber()) {
        output.writeEnum(5, mailStatus_);
      }
      if (createTime_ != 0L) {
        output.writeInt64(6, createTime_);
      }
      if (expireTime_ != 0L) {
        output.writeInt64(7, expireTime_);
      }
      for (int i = 0; i < param_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, param_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMailIdxBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mailIdx_);
      }
      if (mailTemplateId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, mailTemplateId_);
      }
      for (int i = 0; i < rewards_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, rewards_.get(i));
      }
      if (mailStatus_ != protocol.Mail.MailStatusEnum.MSE_NoAttachmentUnread.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, mailStatus_);
      }
      if (createTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, createTime_);
      }
      if (expireTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, expireTime_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < param_.size(); i++) {
          dataSize += computeStringSizeNoTag(param_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getParamList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.MailDB.DB_MailInfo)) {
        return super.equals(obj);
      }
      protocol.MailDB.DB_MailInfo other = (protocol.MailDB.DB_MailInfo) obj;

      boolean result = true;
      result = result && getMailIdx()
          .equals(other.getMailIdx());
      result = result && (getMailTemplateId()
          == other.getMailTemplateId());
      result = result && getRewardsList()
          .equals(other.getRewardsList());
      result = result && mailStatus_ == other.mailStatus_;
      result = result && (getCreateTime()
          == other.getCreateTime());
      result = result && (getExpireTime()
          == other.getExpireTime());
      result = result && getParamList()
          .equals(other.getParamList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAILIDX_FIELD_NUMBER;
      hash = (53 * hash) + getMailIdx().hashCode();
      hash = (37 * hash) + MAILTEMPLATEID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getMailTemplateId());
      if (getRewardsCount() > 0) {
        hash = (37 * hash) + REWARDS_FIELD_NUMBER;
        hash = (53 * hash) + getRewardsList().hashCode();
      }
      hash = (37 * hash) + MAILSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + mailStatus_;
      hash = (37 * hash) + CREATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreateTime());
      hash = (37 * hash) + EXPIRETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExpireTime());
      if (getParamCount() > 0) {
        hash = (37 * hash) + PARAM_FIELD_NUMBER;
        hash = (53 * hash) + getParamList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.MailDB.DB_MailInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MailDB.DB_MailInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MailDB.DB_MailInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MailDB.DB_MailInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MailDB.DB_MailInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.MailDB.DB_MailInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.MailDB.DB_MailInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.MailDB.DB_MailInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.MailDB.DB_MailInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.MailDB.DB_MailInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.MailDB.DB_MailInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.MailDB.DB_MailInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.MailDB.DB_MailInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DB_MailInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DB_MailInfo)
        protocol.MailDB.DB_MailInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.MailDB.internal_static_DB_MailInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.MailDB.internal_static_DB_MailInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.MailDB.DB_MailInfo.class, protocol.MailDB.DB_MailInfo.Builder.class);
      }

      // Construct using protocol.MailDB.DB_MailInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getRewardsFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        mailIdx_ = "";

        mailTemplateId_ = 0L;

        if (rewardsBuilder_ == null) {
          rewards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          rewardsBuilder_.clear();
        }
        mailStatus_ = 0;

        createTime_ = 0L;

        expireTime_ = 0L;

        param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.MailDB.internal_static_DB_MailInfo_descriptor;
      }

      public protocol.MailDB.DB_MailInfo getDefaultInstanceForType() {
        return protocol.MailDB.DB_MailInfo.getDefaultInstance();
      }

      public protocol.MailDB.DB_MailInfo build() {
        protocol.MailDB.DB_MailInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.MailDB.DB_MailInfo buildPartial() {
        protocol.MailDB.DB_MailInfo result = new protocol.MailDB.DB_MailInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.mailIdx_ = mailIdx_;
        result.mailTemplateId_ = mailTemplateId_;
        if (rewardsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            rewards_ = java.util.Collections.unmodifiableList(rewards_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.rewards_ = rewards_;
        } else {
          result.rewards_ = rewardsBuilder_.build();
        }
        result.mailStatus_ = mailStatus_;
        result.createTime_ = createTime_;
        result.expireTime_ = expireTime_;
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          param_ = param_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.param_ = param_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.MailDB.DB_MailInfo) {
          return mergeFrom((protocol.MailDB.DB_MailInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.MailDB.DB_MailInfo other) {
        if (other == protocol.MailDB.DB_MailInfo.getDefaultInstance()) return this;
        if (!other.getMailIdx().isEmpty()) {
          mailIdx_ = other.mailIdx_;
          onChanged();
        }
        if (other.getMailTemplateId() != 0L) {
          setMailTemplateId(other.getMailTemplateId());
        }
        if (rewardsBuilder_ == null) {
          if (!other.rewards_.isEmpty()) {
            if (rewards_.isEmpty()) {
              rewards_ = other.rewards_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensureRewardsIsMutable();
              rewards_.addAll(other.rewards_);
            }
            onChanged();
          }
        } else {
          if (!other.rewards_.isEmpty()) {
            if (rewardsBuilder_.isEmpty()) {
              rewardsBuilder_.dispose();
              rewardsBuilder_ = null;
              rewards_ = other.rewards_;
              bitField0_ = (bitField0_ & ~0x00000004);
              rewardsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getRewardsFieldBuilder() : null;
            } else {
              rewardsBuilder_.addAllMessages(other.rewards_);
            }
          }
        }
        if (other.mailStatus_ != 0) {
          setMailStatusValue(other.getMailStatusValue());
        }
        if (other.getCreateTime() != 0L) {
          setCreateTime(other.getCreateTime());
        }
        if (other.getExpireTime() != 0L) {
          setExpireTime(other.getExpireTime());
        }
        if (!other.param_.isEmpty()) {
          if (param_.isEmpty()) {
            param_ = other.param_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureParamIsMutable();
            param_.addAll(other.param_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.MailDB.DB_MailInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.MailDB.DB_MailInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object mailIdx_ = "";
      /**
       * <code>string mailIdx = 1;</code>
       */
      public java.lang.String getMailIdx() {
        java.lang.Object ref = mailIdx_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          mailIdx_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string mailIdx = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMailIdxBytes() {
        java.lang.Object ref = mailIdx_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mailIdx_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string mailIdx = 1;</code>
       */
      public Builder setMailIdx(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mailIdx_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string mailIdx = 1;</code>
       */
      public Builder clearMailIdx() {
        
        mailIdx_ = getDefaultInstance().getMailIdx();
        onChanged();
        return this;
      }
      /**
       * <code>string mailIdx = 1;</code>
       */
      public Builder setMailIdxBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        mailIdx_ = value;
        onChanged();
        return this;
      }

      private long mailTemplateId_ ;
      /**
       * <code>int64 mailTemplateId = 3;</code>
       */
      public long getMailTemplateId() {
        return mailTemplateId_;
      }
      /**
       * <code>int64 mailTemplateId = 3;</code>
       */
      public Builder setMailTemplateId(long value) {
        
        mailTemplateId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 mailTemplateId = 3;</code>
       */
      public Builder clearMailTemplateId() {
        
        mailTemplateId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<protocol.Common.Reward> rewards_ =
        java.util.Collections.emptyList();
      private void ensureRewardsIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          rewards_ = new java.util.ArrayList<protocol.Common.Reward>(rewards_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Common.Reward, protocol.Common.Reward.Builder, protocol.Common.RewardOrBuilder> rewardsBuilder_;

      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public java.util.List<protocol.Common.Reward> getRewardsList() {
        if (rewardsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(rewards_);
        } else {
          return rewardsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public int getRewardsCount() {
        if (rewardsBuilder_ == null) {
          return rewards_.size();
        } else {
          return rewardsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public protocol.Common.Reward getRewards(int index) {
        if (rewardsBuilder_ == null) {
          return rewards_.get(index);
        } else {
          return rewardsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public Builder setRewards(
          int index, protocol.Common.Reward value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.set(index, value);
          onChanged();
        } else {
          rewardsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public Builder setRewards(
          int index, protocol.Common.Reward.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.set(index, builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public Builder addRewards(protocol.Common.Reward value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.add(value);
          onChanged();
        } else {
          rewardsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public Builder addRewards(
          int index, protocol.Common.Reward value) {
        if (rewardsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRewardsIsMutable();
          rewards_.add(index, value);
          onChanged();
        } else {
          rewardsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public Builder addRewards(
          protocol.Common.Reward.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.add(builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public Builder addRewards(
          int index, protocol.Common.Reward.Builder builderForValue) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.add(index, builderForValue.build());
          onChanged();
        } else {
          rewardsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public Builder addAllRewards(
          java.lang.Iterable<? extends protocol.Common.Reward> values) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, rewards_);
          onChanged();
        } else {
          rewardsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public Builder clearRewards() {
        if (rewardsBuilder_ == null) {
          rewards_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          rewardsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public Builder removeRewards(int index) {
        if (rewardsBuilder_ == null) {
          ensureRewardsIsMutable();
          rewards_.remove(index);
          onChanged();
        } else {
          rewardsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public protocol.Common.Reward.Builder getRewardsBuilder(
          int index) {
        return getRewardsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public protocol.Common.RewardOrBuilder getRewardsOrBuilder(
          int index) {
        if (rewardsBuilder_ == null) {
          return rewards_.get(index);  } else {
          return rewardsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public java.util.List<? extends protocol.Common.RewardOrBuilder> 
           getRewardsOrBuilderList() {
        if (rewardsBuilder_ != null) {
          return rewardsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(rewards_);
        }
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public protocol.Common.Reward.Builder addRewardsBuilder() {
        return getRewardsFieldBuilder().addBuilder(
            protocol.Common.Reward.getDefaultInstance());
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public protocol.Common.Reward.Builder addRewardsBuilder(
          int index) {
        return getRewardsFieldBuilder().addBuilder(
            index, protocol.Common.Reward.getDefaultInstance());
      }
      /**
       * <code>repeated .Reward rewards = 4;</code>
       */
      public java.util.List<protocol.Common.Reward.Builder> 
           getRewardsBuilderList() {
        return getRewardsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.Common.Reward, protocol.Common.Reward.Builder, protocol.Common.RewardOrBuilder> 
          getRewardsFieldBuilder() {
        if (rewardsBuilder_ == null) {
          rewardsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.Common.Reward, protocol.Common.Reward.Builder, protocol.Common.RewardOrBuilder>(
                  rewards_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          rewards_ = null;
        }
        return rewardsBuilder_;
      }

      private int mailStatus_ = 0;
      /**
       * <code>.MailStatusEnum mailStatus = 5;</code>
       */
      public int getMailStatusValue() {
        return mailStatus_;
      }
      /**
       * <code>.MailStatusEnum mailStatus = 5;</code>
       */
      public Builder setMailStatusValue(int value) {
        mailStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.MailStatusEnum mailStatus = 5;</code>
       */
      public protocol.Mail.MailStatusEnum getMailStatus() {
        protocol.Mail.MailStatusEnum result = protocol.Mail.MailStatusEnum.valueOf(mailStatus_);
        return result == null ? protocol.Mail.MailStatusEnum.UNRECOGNIZED : result;
      }
      /**
       * <code>.MailStatusEnum mailStatus = 5;</code>
       */
      public Builder setMailStatus(protocol.Mail.MailStatusEnum value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        mailStatus_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.MailStatusEnum mailStatus = 5;</code>
       */
      public Builder clearMailStatus() {
        
        mailStatus_ = 0;
        onChanged();
        return this;
      }

      private long createTime_ ;
      /**
       * <code>int64 createTime = 6;</code>
       */
      public long getCreateTime() {
        return createTime_;
      }
      /**
       * <code>int64 createTime = 6;</code>
       */
      public Builder setCreateTime(long value) {
        
        createTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 createTime = 6;</code>
       */
      public Builder clearCreateTime() {
        
        createTime_ = 0L;
        onChanged();
        return this;
      }

      private long expireTime_ ;
      /**
       * <code>int64 expireTime = 7;</code>
       */
      public long getExpireTime() {
        return expireTime_;
      }
      /**
       * <code>int64 expireTime = 7;</code>
       */
      public Builder setExpireTime(long value) {
        
        expireTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 expireTime = 7;</code>
       */
      public Builder clearExpireTime() {
        
        expireTime_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureParamIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          param_ = new com.google.protobuf.LazyStringArrayList(param_);
          bitField0_ |= 0x00000040;
         }
      }
      /**
       * <code>repeated string param = 8;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getParamList() {
        return param_.getUnmodifiableView();
      }
      /**
       * <code>repeated string param = 8;</code>
       */
      public int getParamCount() {
        return param_.size();
      }
      /**
       * <code>repeated string param = 8;</code>
       */
      public java.lang.String getParam(int index) {
        return param_.get(index);
      }
      /**
       * <code>repeated string param = 8;</code>
       */
      public com.google.protobuf.ByteString
          getParamBytes(int index) {
        return param_.getByteString(index);
      }
      /**
       * <code>repeated string param = 8;</code>
       */
      public Builder setParam(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamIsMutable();
        param_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param = 8;</code>
       */
      public Builder addParam(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureParamIsMutable();
        param_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param = 8;</code>
       */
      public Builder addAllParam(
          java.lang.Iterable<java.lang.String> values) {
        ensureParamIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, param_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param = 8;</code>
       */
      public Builder clearParam() {
        param_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string param = 8;</code>
       */
      public Builder addParamBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureParamIsMutable();
        param_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DB_MailInfo)
    }

    // @@protoc_insertion_point(class_scope:DB_MailInfo)
    private static final protocol.MailDB.DB_MailInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.MailDB.DB_MailInfo();
    }

    public static protocol.MailDB.DB_MailInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DB_MailInfo>
        PARSER = new com.google.protobuf.AbstractParser<DB_MailInfo>() {
      public DB_MailInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DB_MailInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DB_MailInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DB_MailInfo> getParserForType() {
      return PARSER;
    }

    public protocol.MailDB.DB_MailInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_MailBox_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_MailBox_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_MailBox_MailsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_MailBox_MailsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_MailInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_MailInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014MailDB.proto\032\nMail.proto\032\014Common.proto" +
      "\"o\n\nDB_MailBox\022%\n\005mails\030\002 \003(\0132\026.DB_MailB" +
      "ox.MailsEntry\032:\n\nMailsEntry\022\013\n\003key\030\001 \001(\t" +
      "\022\033\n\005value\030\002 \001(\0132\014.DB_MailInfo:\0028\001\"\254\001\n\013DB" +
      "_MailInfo\022\017\n\007mailIdx\030\001 \001(\t\022\026\n\016mailTempla" +
      "teId\030\003 \001(\003\022\030\n\007rewards\030\004 \003(\0132\007.Reward\022#\n\n" +
      "mailStatus\030\005 \001(\0162\017.MailStatusEnum\022\022\n\ncre" +
      "ateTime\030\006 \001(\003\022\022\n\nexpireTime\030\007 \001(\003\022\r\n\005par" +
      "am\030\010 \003(\tB\033\n\010protocol\252\002\016ETHotfix.Protob\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.Mail.getDescriptor(),
          protocol.Common.getDescriptor(),
        }, assigner);
    internal_static_DB_MailBox_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DB_MailBox_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_MailBox_descriptor,
        new java.lang.String[] { "Mails", });
    internal_static_DB_MailBox_MailsEntry_descriptor =
      internal_static_DB_MailBox_descriptor.getNestedTypes().get(0);
    internal_static_DB_MailBox_MailsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_MailBox_MailsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_DB_MailInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DB_MailInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_MailInfo_descriptor,
        new java.lang.String[] { "MailIdx", "MailTemplateId", "Rewards", "MailStatus", "CreateTime", "ExpireTime", "Param", });
    protocol.Mail.getDescriptor();
    protocol.Common.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
