-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQguQq/ModPSVbzDD7H
hQseObRWo994NBsYul7QN6qwP9mgCgYIKoZIzj0DAQehRANCAARsyNgNB/twNCOo
idHNV3hAIos1tP4rg8SsE8oY5QpTHPnzazi+fKtIu90nNWJvNxxrhxvcey7IWuMP
CHHZ8t79
-----END PRIVATE KEY-----