-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtHKLJRodHQb5nuhM
Tuv2o1YgrIM9iMMDNsbfdaS6NKGgCgYIKoZIzj0DAQehRANCAATMQRxNHlIFA01l
hSV1YZ9NAgIoES3XpbIVeZY9/psCM+8V3X3wvUFkqp0HMQOAVjrBZXul+5tc2vcK
CDyC0ESU
-----END PRIVATE KEY-----