// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BattleRecordDB.proto

package protocol;

public final class BattleRecordDB {
  private BattleRecordDB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DB_ServerBattleRecordOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DB_ServerBattleRecord)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.SC_EnterFight enterFight = 1;</code>
     */
    boolean hasEnterFight();
    /**
     * <code>.SC_EnterFight enterFight = 1;</code>
     */
    protocol.Battle.SC_EnterFight getEnterFight();
    /**
     * <code>.SC_EnterFight enterFight = 1;</code>
     */
    protocol.Battle.SC_EnterFightOrBuilder getEnterFightOrBuilder();

    /**
     * <code>repeated .SC_FrameData frameData = 2;</code>
     */
    java.util.List<protocol.BattleMono.SC_FrameData> 
        getFrameDataList();
    /**
     * <code>repeated .SC_FrameData frameData = 2;</code>
     */
    protocol.BattleMono.SC_FrameData getFrameData(int index);
    /**
     * <code>repeated .SC_FrameData frameData = 2;</code>
     */
    int getFrameDataCount();
    /**
     * <code>repeated .SC_FrameData frameData = 2;</code>
     */
    java.util.List<? extends protocol.BattleMono.SC_FrameDataOrBuilder> 
        getFrameDataOrBuilderList();
    /**
     * <code>repeated .SC_FrameData frameData = 2;</code>
     */
    protocol.BattleMono.SC_FrameDataOrBuilder getFrameDataOrBuilder(
        int index);

    /**
     * <code>.BattleStatisticData statisticData = 3;</code>
     */
    boolean hasStatisticData();
    /**
     * <code>.BattleStatisticData statisticData = 3;</code>
     */
    protocol.Battle.BattleStatisticData getStatisticData();
    /**
     * <code>.BattleStatisticData statisticData = 3;</code>
     */
    protocol.Battle.BattleStatisticDataOrBuilder getStatisticDataOrBuilder();

    /**
     * <code>.SC_BattleResult battleResult = 4;</code>
     */
    boolean hasBattleResult();
    /**
     * <code>.SC_BattleResult battleResult = 4;</code>
     */
    protocol.Battle.SC_BattleResult getBattleResult();
    /**
     * <code>.SC_BattleResult battleResult = 4;</code>
     */
    protocol.Battle.SC_BattleResultOrBuilder getBattleResultOrBuilder();
  }
  /**
   * Protobuf type {@code DB_ServerBattleRecord}
   */
  public  static final class DB_ServerBattleRecord extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DB_ServerBattleRecord)
      DB_ServerBattleRecordOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DB_ServerBattleRecord.newBuilder() to construct.
    private DB_ServerBattleRecord(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DB_ServerBattleRecord() {
      frameData_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DB_ServerBattleRecord(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protocol.Battle.SC_EnterFight.Builder subBuilder = null;
              if (enterFight_ != null) {
                subBuilder = enterFight_.toBuilder();
              }
              enterFight_ = input.readMessage(protocol.Battle.SC_EnterFight.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(enterFight_);
                enterFight_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                frameData_ = new java.util.ArrayList<protocol.BattleMono.SC_FrameData>();
                mutable_bitField0_ |= 0x00000002;
              }
              frameData_.add(
                  input.readMessage(protocol.BattleMono.SC_FrameData.parser(), extensionRegistry));
              break;
            }
            case 26: {
              protocol.Battle.BattleStatisticData.Builder subBuilder = null;
              if (statisticData_ != null) {
                subBuilder = statisticData_.toBuilder();
              }
              statisticData_ = input.readMessage(protocol.Battle.BattleStatisticData.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(statisticData_);
                statisticData_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              protocol.Battle.SC_BattleResult.Builder subBuilder = null;
              if (battleResult_ != null) {
                subBuilder = battleResult_.toBuilder();
              }
              battleResult_ = input.readMessage(protocol.Battle.SC_BattleResult.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(battleResult_);
                battleResult_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          frameData_ = java.util.Collections.unmodifiableList(frameData_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.BattleRecordDB.internal_static_DB_ServerBattleRecord_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.BattleRecordDB.internal_static_DB_ServerBattleRecord_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.BattleRecordDB.DB_ServerBattleRecord.class, protocol.BattleRecordDB.DB_ServerBattleRecord.Builder.class);
    }

    private int bitField0_;
    public static final int ENTERFIGHT_FIELD_NUMBER = 1;
    private protocol.Battle.SC_EnterFight enterFight_;
    /**
     * <code>.SC_EnterFight enterFight = 1;</code>
     */
    public boolean hasEnterFight() {
      return enterFight_ != null;
    }
    /**
     * <code>.SC_EnterFight enterFight = 1;</code>
     */
    public protocol.Battle.SC_EnterFight getEnterFight() {
      return enterFight_ == null ? protocol.Battle.SC_EnterFight.getDefaultInstance() : enterFight_;
    }
    /**
     * <code>.SC_EnterFight enterFight = 1;</code>
     */
    public protocol.Battle.SC_EnterFightOrBuilder getEnterFightOrBuilder() {
      return getEnterFight();
    }

    public static final int FRAMEDATA_FIELD_NUMBER = 2;
    private java.util.List<protocol.BattleMono.SC_FrameData> frameData_;
    /**
     * <code>repeated .SC_FrameData frameData = 2;</code>
     */
    public java.util.List<protocol.BattleMono.SC_FrameData> getFrameDataList() {
      return frameData_;
    }
    /**
     * <code>repeated .SC_FrameData frameData = 2;</code>
     */
    public java.util.List<? extends protocol.BattleMono.SC_FrameDataOrBuilder> 
        getFrameDataOrBuilderList() {
      return frameData_;
    }
    /**
     * <code>repeated .SC_FrameData frameData = 2;</code>
     */
    public int getFrameDataCount() {
      return frameData_.size();
    }
    /**
     * <code>repeated .SC_FrameData frameData = 2;</code>
     */
    public protocol.BattleMono.SC_FrameData getFrameData(int index) {
      return frameData_.get(index);
    }
    /**
     * <code>repeated .SC_FrameData frameData = 2;</code>
     */
    public protocol.BattleMono.SC_FrameDataOrBuilder getFrameDataOrBuilder(
        int index) {
      return frameData_.get(index);
    }

    public static final int STATISTICDATA_FIELD_NUMBER = 3;
    private protocol.Battle.BattleStatisticData statisticData_;
    /**
     * <code>.BattleStatisticData statisticData = 3;</code>
     */
    public boolean hasStatisticData() {
      return statisticData_ != null;
    }
    /**
     * <code>.BattleStatisticData statisticData = 3;</code>
     */
    public protocol.Battle.BattleStatisticData getStatisticData() {
      return statisticData_ == null ? protocol.Battle.BattleStatisticData.getDefaultInstance() : statisticData_;
    }
    /**
     * <code>.BattleStatisticData statisticData = 3;</code>
     */
    public protocol.Battle.BattleStatisticDataOrBuilder getStatisticDataOrBuilder() {
      return getStatisticData();
    }

    public static final int BATTLERESULT_FIELD_NUMBER = 4;
    private protocol.Battle.SC_BattleResult battleResult_;
    /**
     * <code>.SC_BattleResult battleResult = 4;</code>
     */
    public boolean hasBattleResult() {
      return battleResult_ != null;
    }
    /**
     * <code>.SC_BattleResult battleResult = 4;</code>
     */
    public protocol.Battle.SC_BattleResult getBattleResult() {
      return battleResult_ == null ? protocol.Battle.SC_BattleResult.getDefaultInstance() : battleResult_;
    }
    /**
     * <code>.SC_BattleResult battleResult = 4;</code>
     */
    public protocol.Battle.SC_BattleResultOrBuilder getBattleResultOrBuilder() {
      return getBattleResult();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (enterFight_ != null) {
        output.writeMessage(1, getEnterFight());
      }
      for (int i = 0; i < frameData_.size(); i++) {
        output.writeMessage(2, frameData_.get(i));
      }
      if (statisticData_ != null) {
        output.writeMessage(3, getStatisticData());
      }
      if (battleResult_ != null) {
        output.writeMessage(4, getBattleResult());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (enterFight_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getEnterFight());
      }
      for (int i = 0; i < frameData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, frameData_.get(i));
      }
      if (statisticData_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getStatisticData());
      }
      if (battleResult_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getBattleResult());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.BattleRecordDB.DB_ServerBattleRecord)) {
        return super.equals(obj);
      }
      protocol.BattleRecordDB.DB_ServerBattleRecord other = (protocol.BattleRecordDB.DB_ServerBattleRecord) obj;

      boolean result = true;
      result = result && (hasEnterFight() == other.hasEnterFight());
      if (hasEnterFight()) {
        result = result && getEnterFight()
            .equals(other.getEnterFight());
      }
      result = result && getFrameDataList()
          .equals(other.getFrameDataList());
      result = result && (hasStatisticData() == other.hasStatisticData());
      if (hasStatisticData()) {
        result = result && getStatisticData()
            .equals(other.getStatisticData());
      }
      result = result && (hasBattleResult() == other.hasBattleResult());
      if (hasBattleResult()) {
        result = result && getBattleResult()
            .equals(other.getBattleResult());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEnterFight()) {
        hash = (37 * hash) + ENTERFIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getEnterFight().hashCode();
      }
      if (getFrameDataCount() > 0) {
        hash = (37 * hash) + FRAMEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getFrameDataList().hashCode();
      }
      if (hasStatisticData()) {
        hash = (37 * hash) + STATISTICDATA_FIELD_NUMBER;
        hash = (53 * hash) + getStatisticData().hashCode();
      }
      if (hasBattleResult()) {
        hash = (37 * hash) + BATTLERESULT_FIELD_NUMBER;
        hash = (53 * hash) + getBattleResult().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.BattleRecordDB.DB_ServerBattleRecord parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.BattleRecordDB.DB_ServerBattleRecord prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DB_ServerBattleRecord}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DB_ServerBattleRecord)
        protocol.BattleRecordDB.DB_ServerBattleRecordOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.BattleRecordDB.internal_static_DB_ServerBattleRecord_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.BattleRecordDB.internal_static_DB_ServerBattleRecord_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.BattleRecordDB.DB_ServerBattleRecord.class, protocol.BattleRecordDB.DB_ServerBattleRecord.Builder.class);
      }

      // Construct using protocol.BattleRecordDB.DB_ServerBattleRecord.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getFrameDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (enterFightBuilder_ == null) {
          enterFight_ = null;
        } else {
          enterFight_ = null;
          enterFightBuilder_ = null;
        }
        if (frameDataBuilder_ == null) {
          frameData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          frameDataBuilder_.clear();
        }
        if (statisticDataBuilder_ == null) {
          statisticData_ = null;
        } else {
          statisticData_ = null;
          statisticDataBuilder_ = null;
        }
        if (battleResultBuilder_ == null) {
          battleResult_ = null;
        } else {
          battleResult_ = null;
          battleResultBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.BattleRecordDB.internal_static_DB_ServerBattleRecord_descriptor;
      }

      public protocol.BattleRecordDB.DB_ServerBattleRecord getDefaultInstanceForType() {
        return protocol.BattleRecordDB.DB_ServerBattleRecord.getDefaultInstance();
      }

      public protocol.BattleRecordDB.DB_ServerBattleRecord build() {
        protocol.BattleRecordDB.DB_ServerBattleRecord result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.BattleRecordDB.DB_ServerBattleRecord buildPartial() {
        protocol.BattleRecordDB.DB_ServerBattleRecord result = new protocol.BattleRecordDB.DB_ServerBattleRecord(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (enterFightBuilder_ == null) {
          result.enterFight_ = enterFight_;
        } else {
          result.enterFight_ = enterFightBuilder_.build();
        }
        if (frameDataBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            frameData_ = java.util.Collections.unmodifiableList(frameData_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.frameData_ = frameData_;
        } else {
          result.frameData_ = frameDataBuilder_.build();
        }
        if (statisticDataBuilder_ == null) {
          result.statisticData_ = statisticData_;
        } else {
          result.statisticData_ = statisticDataBuilder_.build();
        }
        if (battleResultBuilder_ == null) {
          result.battleResult_ = battleResult_;
        } else {
          result.battleResult_ = battleResultBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.BattleRecordDB.DB_ServerBattleRecord) {
          return mergeFrom((protocol.BattleRecordDB.DB_ServerBattleRecord)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.BattleRecordDB.DB_ServerBattleRecord other) {
        if (other == protocol.BattleRecordDB.DB_ServerBattleRecord.getDefaultInstance()) return this;
        if (other.hasEnterFight()) {
          mergeEnterFight(other.getEnterFight());
        }
        if (frameDataBuilder_ == null) {
          if (!other.frameData_.isEmpty()) {
            if (frameData_.isEmpty()) {
              frameData_ = other.frameData_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureFrameDataIsMutable();
              frameData_.addAll(other.frameData_);
            }
            onChanged();
          }
        } else {
          if (!other.frameData_.isEmpty()) {
            if (frameDataBuilder_.isEmpty()) {
              frameDataBuilder_.dispose();
              frameDataBuilder_ = null;
              frameData_ = other.frameData_;
              bitField0_ = (bitField0_ & ~0x00000002);
              frameDataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getFrameDataFieldBuilder() : null;
            } else {
              frameDataBuilder_.addAllMessages(other.frameData_);
            }
          }
        }
        if (other.hasStatisticData()) {
          mergeStatisticData(other.getStatisticData());
        }
        if (other.hasBattleResult()) {
          mergeBattleResult(other.getBattleResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.BattleRecordDB.DB_ServerBattleRecord parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.BattleRecordDB.DB_ServerBattleRecord) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protocol.Battle.SC_EnterFight enterFight_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.Battle.SC_EnterFight, protocol.Battle.SC_EnterFight.Builder, protocol.Battle.SC_EnterFightOrBuilder> enterFightBuilder_;
      /**
       * <code>.SC_EnterFight enterFight = 1;</code>
       */
      public boolean hasEnterFight() {
        return enterFightBuilder_ != null || enterFight_ != null;
      }
      /**
       * <code>.SC_EnterFight enterFight = 1;</code>
       */
      public protocol.Battle.SC_EnterFight getEnterFight() {
        if (enterFightBuilder_ == null) {
          return enterFight_ == null ? protocol.Battle.SC_EnterFight.getDefaultInstance() : enterFight_;
        } else {
          return enterFightBuilder_.getMessage();
        }
      }
      /**
       * <code>.SC_EnterFight enterFight = 1;</code>
       */
      public Builder setEnterFight(protocol.Battle.SC_EnterFight value) {
        if (enterFightBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          enterFight_ = value;
          onChanged();
        } else {
          enterFightBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.SC_EnterFight enterFight = 1;</code>
       */
      public Builder setEnterFight(
          protocol.Battle.SC_EnterFight.Builder builderForValue) {
        if (enterFightBuilder_ == null) {
          enterFight_ = builderForValue.build();
          onChanged();
        } else {
          enterFightBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.SC_EnterFight enterFight = 1;</code>
       */
      public Builder mergeEnterFight(protocol.Battle.SC_EnterFight value) {
        if (enterFightBuilder_ == null) {
          if (enterFight_ != null) {
            enterFight_ =
              protocol.Battle.SC_EnterFight.newBuilder(enterFight_).mergeFrom(value).buildPartial();
          } else {
            enterFight_ = value;
          }
          onChanged();
        } else {
          enterFightBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.SC_EnterFight enterFight = 1;</code>
       */
      public Builder clearEnterFight() {
        if (enterFightBuilder_ == null) {
          enterFight_ = null;
          onChanged();
        } else {
          enterFight_ = null;
          enterFightBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.SC_EnterFight enterFight = 1;</code>
       */
      public protocol.Battle.SC_EnterFight.Builder getEnterFightBuilder() {
        
        onChanged();
        return getEnterFightFieldBuilder().getBuilder();
      }
      /**
       * <code>.SC_EnterFight enterFight = 1;</code>
       */
      public protocol.Battle.SC_EnterFightOrBuilder getEnterFightOrBuilder() {
        if (enterFightBuilder_ != null) {
          return enterFightBuilder_.getMessageOrBuilder();
        } else {
          return enterFight_ == null ?
              protocol.Battle.SC_EnterFight.getDefaultInstance() : enterFight_;
        }
      }
      /**
       * <code>.SC_EnterFight enterFight = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.Battle.SC_EnterFight, protocol.Battle.SC_EnterFight.Builder, protocol.Battle.SC_EnterFightOrBuilder> 
          getEnterFightFieldBuilder() {
        if (enterFightBuilder_ == null) {
          enterFightBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protocol.Battle.SC_EnterFight, protocol.Battle.SC_EnterFight.Builder, protocol.Battle.SC_EnterFightOrBuilder>(
                  getEnterFight(),
                  getParentForChildren(),
                  isClean());
          enterFight_ = null;
        }
        return enterFightBuilder_;
      }

      private java.util.List<protocol.BattleMono.SC_FrameData> frameData_ =
        java.util.Collections.emptyList();
      private void ensureFrameDataIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          frameData_ = new java.util.ArrayList<protocol.BattleMono.SC_FrameData>(frameData_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.BattleMono.SC_FrameData, protocol.BattleMono.SC_FrameData.Builder, protocol.BattleMono.SC_FrameDataOrBuilder> frameDataBuilder_;

      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public java.util.List<protocol.BattleMono.SC_FrameData> getFrameDataList() {
        if (frameDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(frameData_);
        } else {
          return frameDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public int getFrameDataCount() {
        if (frameDataBuilder_ == null) {
          return frameData_.size();
        } else {
          return frameDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public protocol.BattleMono.SC_FrameData getFrameData(int index) {
        if (frameDataBuilder_ == null) {
          return frameData_.get(index);
        } else {
          return frameDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public Builder setFrameData(
          int index, protocol.BattleMono.SC_FrameData value) {
        if (frameDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFrameDataIsMutable();
          frameData_.set(index, value);
          onChanged();
        } else {
          frameDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public Builder setFrameData(
          int index, protocol.BattleMono.SC_FrameData.Builder builderForValue) {
        if (frameDataBuilder_ == null) {
          ensureFrameDataIsMutable();
          frameData_.set(index, builderForValue.build());
          onChanged();
        } else {
          frameDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public Builder addFrameData(protocol.BattleMono.SC_FrameData value) {
        if (frameDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFrameDataIsMutable();
          frameData_.add(value);
          onChanged();
        } else {
          frameDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public Builder addFrameData(
          int index, protocol.BattleMono.SC_FrameData value) {
        if (frameDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFrameDataIsMutable();
          frameData_.add(index, value);
          onChanged();
        } else {
          frameDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public Builder addFrameData(
          protocol.BattleMono.SC_FrameData.Builder builderForValue) {
        if (frameDataBuilder_ == null) {
          ensureFrameDataIsMutable();
          frameData_.add(builderForValue.build());
          onChanged();
        } else {
          frameDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public Builder addFrameData(
          int index, protocol.BattleMono.SC_FrameData.Builder builderForValue) {
        if (frameDataBuilder_ == null) {
          ensureFrameDataIsMutable();
          frameData_.add(index, builderForValue.build());
          onChanged();
        } else {
          frameDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public Builder addAllFrameData(
          java.lang.Iterable<? extends protocol.BattleMono.SC_FrameData> values) {
        if (frameDataBuilder_ == null) {
          ensureFrameDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, frameData_);
          onChanged();
        } else {
          frameDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public Builder clearFrameData() {
        if (frameDataBuilder_ == null) {
          frameData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          frameDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public Builder removeFrameData(int index) {
        if (frameDataBuilder_ == null) {
          ensureFrameDataIsMutable();
          frameData_.remove(index);
          onChanged();
        } else {
          frameDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public protocol.BattleMono.SC_FrameData.Builder getFrameDataBuilder(
          int index) {
        return getFrameDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public protocol.BattleMono.SC_FrameDataOrBuilder getFrameDataOrBuilder(
          int index) {
        if (frameDataBuilder_ == null) {
          return frameData_.get(index);  } else {
          return frameDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public java.util.List<? extends protocol.BattleMono.SC_FrameDataOrBuilder> 
           getFrameDataOrBuilderList() {
        if (frameDataBuilder_ != null) {
          return frameDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(frameData_);
        }
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public protocol.BattleMono.SC_FrameData.Builder addFrameDataBuilder() {
        return getFrameDataFieldBuilder().addBuilder(
            protocol.BattleMono.SC_FrameData.getDefaultInstance());
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public protocol.BattleMono.SC_FrameData.Builder addFrameDataBuilder(
          int index) {
        return getFrameDataFieldBuilder().addBuilder(
            index, protocol.BattleMono.SC_FrameData.getDefaultInstance());
      }
      /**
       * <code>repeated .SC_FrameData frameData = 2;</code>
       */
      public java.util.List<protocol.BattleMono.SC_FrameData.Builder> 
           getFrameDataBuilderList() {
        return getFrameDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          protocol.BattleMono.SC_FrameData, protocol.BattleMono.SC_FrameData.Builder, protocol.BattleMono.SC_FrameDataOrBuilder> 
          getFrameDataFieldBuilder() {
        if (frameDataBuilder_ == null) {
          frameDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              protocol.BattleMono.SC_FrameData, protocol.BattleMono.SC_FrameData.Builder, protocol.BattleMono.SC_FrameDataOrBuilder>(
                  frameData_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          frameData_ = null;
        }
        return frameDataBuilder_;
      }

      private protocol.Battle.BattleStatisticData statisticData_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.Battle.BattleStatisticData, protocol.Battle.BattleStatisticData.Builder, protocol.Battle.BattleStatisticDataOrBuilder> statisticDataBuilder_;
      /**
       * <code>.BattleStatisticData statisticData = 3;</code>
       */
      public boolean hasStatisticData() {
        return statisticDataBuilder_ != null || statisticData_ != null;
      }
      /**
       * <code>.BattleStatisticData statisticData = 3;</code>
       */
      public protocol.Battle.BattleStatisticData getStatisticData() {
        if (statisticDataBuilder_ == null) {
          return statisticData_ == null ? protocol.Battle.BattleStatisticData.getDefaultInstance() : statisticData_;
        } else {
          return statisticDataBuilder_.getMessage();
        }
      }
      /**
       * <code>.BattleStatisticData statisticData = 3;</code>
       */
      public Builder setStatisticData(protocol.Battle.BattleStatisticData value) {
        if (statisticDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          statisticData_ = value;
          onChanged();
        } else {
          statisticDataBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BattleStatisticData statisticData = 3;</code>
       */
      public Builder setStatisticData(
          protocol.Battle.BattleStatisticData.Builder builderForValue) {
        if (statisticDataBuilder_ == null) {
          statisticData_ = builderForValue.build();
          onChanged();
        } else {
          statisticDataBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BattleStatisticData statisticData = 3;</code>
       */
      public Builder mergeStatisticData(protocol.Battle.BattleStatisticData value) {
        if (statisticDataBuilder_ == null) {
          if (statisticData_ != null) {
            statisticData_ =
              protocol.Battle.BattleStatisticData.newBuilder(statisticData_).mergeFrom(value).buildPartial();
          } else {
            statisticData_ = value;
          }
          onChanged();
        } else {
          statisticDataBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BattleStatisticData statisticData = 3;</code>
       */
      public Builder clearStatisticData() {
        if (statisticDataBuilder_ == null) {
          statisticData_ = null;
          onChanged();
        } else {
          statisticData_ = null;
          statisticDataBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BattleStatisticData statisticData = 3;</code>
       */
      public protocol.Battle.BattleStatisticData.Builder getStatisticDataBuilder() {
        
        onChanged();
        return getStatisticDataFieldBuilder().getBuilder();
      }
      /**
       * <code>.BattleStatisticData statisticData = 3;</code>
       */
      public protocol.Battle.BattleStatisticDataOrBuilder getStatisticDataOrBuilder() {
        if (statisticDataBuilder_ != null) {
          return statisticDataBuilder_.getMessageOrBuilder();
        } else {
          return statisticData_ == null ?
              protocol.Battle.BattleStatisticData.getDefaultInstance() : statisticData_;
        }
      }
      /**
       * <code>.BattleStatisticData statisticData = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.Battle.BattleStatisticData, protocol.Battle.BattleStatisticData.Builder, protocol.Battle.BattleStatisticDataOrBuilder> 
          getStatisticDataFieldBuilder() {
        if (statisticDataBuilder_ == null) {
          statisticDataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protocol.Battle.BattleStatisticData, protocol.Battle.BattleStatisticData.Builder, protocol.Battle.BattleStatisticDataOrBuilder>(
                  getStatisticData(),
                  getParentForChildren(),
                  isClean());
          statisticData_ = null;
        }
        return statisticDataBuilder_;
      }

      private protocol.Battle.SC_BattleResult battleResult_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.Battle.SC_BattleResult, protocol.Battle.SC_BattleResult.Builder, protocol.Battle.SC_BattleResultOrBuilder> battleResultBuilder_;
      /**
       * <code>.SC_BattleResult battleResult = 4;</code>
       */
      public boolean hasBattleResult() {
        return battleResultBuilder_ != null || battleResult_ != null;
      }
      /**
       * <code>.SC_BattleResult battleResult = 4;</code>
       */
      public protocol.Battle.SC_BattleResult getBattleResult() {
        if (battleResultBuilder_ == null) {
          return battleResult_ == null ? protocol.Battle.SC_BattleResult.getDefaultInstance() : battleResult_;
        } else {
          return battleResultBuilder_.getMessage();
        }
      }
      /**
       * <code>.SC_BattleResult battleResult = 4;</code>
       */
      public Builder setBattleResult(protocol.Battle.SC_BattleResult value) {
        if (battleResultBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          battleResult_ = value;
          onChanged();
        } else {
          battleResultBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.SC_BattleResult battleResult = 4;</code>
       */
      public Builder setBattleResult(
          protocol.Battle.SC_BattleResult.Builder builderForValue) {
        if (battleResultBuilder_ == null) {
          battleResult_ = builderForValue.build();
          onChanged();
        } else {
          battleResultBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.SC_BattleResult battleResult = 4;</code>
       */
      public Builder mergeBattleResult(protocol.Battle.SC_BattleResult value) {
        if (battleResultBuilder_ == null) {
          if (battleResult_ != null) {
            battleResult_ =
              protocol.Battle.SC_BattleResult.newBuilder(battleResult_).mergeFrom(value).buildPartial();
          } else {
            battleResult_ = value;
          }
          onChanged();
        } else {
          battleResultBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.SC_BattleResult battleResult = 4;</code>
       */
      public Builder clearBattleResult() {
        if (battleResultBuilder_ == null) {
          battleResult_ = null;
          onChanged();
        } else {
          battleResult_ = null;
          battleResultBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.SC_BattleResult battleResult = 4;</code>
       */
      public protocol.Battle.SC_BattleResult.Builder getBattleResultBuilder() {
        
        onChanged();
        return getBattleResultFieldBuilder().getBuilder();
      }
      /**
       * <code>.SC_BattleResult battleResult = 4;</code>
       */
      public protocol.Battle.SC_BattleResultOrBuilder getBattleResultOrBuilder() {
        if (battleResultBuilder_ != null) {
          return battleResultBuilder_.getMessageOrBuilder();
        } else {
          return battleResult_ == null ?
              protocol.Battle.SC_BattleResult.getDefaultInstance() : battleResult_;
        }
      }
      /**
       * <code>.SC_BattleResult battleResult = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.Battle.SC_BattleResult, protocol.Battle.SC_BattleResult.Builder, protocol.Battle.SC_BattleResultOrBuilder> 
          getBattleResultFieldBuilder() {
        if (battleResultBuilder_ == null) {
          battleResultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protocol.Battle.SC_BattleResult, protocol.Battle.SC_BattleResult.Builder, protocol.Battle.SC_BattleResultOrBuilder>(
                  getBattleResult(),
                  getParentForChildren(),
                  isClean());
          battleResult_ = null;
        }
        return battleResultBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DB_ServerBattleRecord)
    }

    // @@protoc_insertion_point(class_scope:DB_ServerBattleRecord)
    private static final protocol.BattleRecordDB.DB_ServerBattleRecord DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.BattleRecordDB.DB_ServerBattleRecord();
    }

    public static protocol.BattleRecordDB.DB_ServerBattleRecord getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DB_ServerBattleRecord>
        PARSER = new com.google.protobuf.AbstractParser<DB_ServerBattleRecord>() {
      public DB_ServerBattleRecord parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DB_ServerBattleRecord(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DB_ServerBattleRecord> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DB_ServerBattleRecord> getParserForType() {
      return PARSER;
    }

    public protocol.BattleRecordDB.DB_ServerBattleRecord getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_ServerBattleRecord_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_ServerBattleRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024BattleRecordDB.proto\032\020BattleMono.proto" +
      "\032\014Battle.proto\"\262\001\n\025DB_ServerBattleRecord" +
      "\022\"\n\nenterFight\030\001 \001(\0132\016.SC_EnterFight\022 \n\t" +
      "frameData\030\002 \003(\0132\r.SC_FrameData\022+\n\rstatis" +
      "ticData\030\003 \001(\0132\024.BattleStatisticData\022&\n\014b" +
      "attleResult\030\004 \001(\0132\020.SC_BattleResultB\033\n\010p" +
      "rotocol\252\002\016ETHotfix.Protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.BattleMono.getDescriptor(),
          protocol.Battle.getDescriptor(),
        }, assigner);
    internal_static_DB_ServerBattleRecord_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DB_ServerBattleRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_ServerBattleRecord_descriptor,
        new java.lang.String[] { "EnterFight", "FrameData", "StatisticData", "BattleResult", });
    protocol.BattleMono.getDescriptor();
    protocol.Battle.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
