// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FarmMineDB.proto

package protocol;

public final class FarmMineDBOuterClass {
  private FarmMineDBOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FarmMineDBOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FarmMineDB)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.FarmMineMyInfo myInfo = 1;</code>
     */
    boolean hasMyInfo();
    /**
     * <code>.FarmMineMyInfo myInfo = 1;</code>
     */
    protocol.FarmMine.FarmMineMyInfo getMyInfo();
    /**
     * <code>.FarmMineMyInfo myInfo = 1;</code>
     */
    protocol.FarmMine.FarmMineMyInfoOrBuilder getMyInfoOrBuilder();

    /**
     * <pre>
     *出价信息
     * </pre>
     *
     * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
     */
    int getOfferInfoCount();
    /**
     * <pre>
     *出价信息
     * </pre>
     *
     * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
     */
    boolean containsOfferInfo(
        int key);
    /**
     * Use {@link #getOfferInfoMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, java.lang.Integer>
    getOfferInfo();
    /**
     * <pre>
     *出价信息
     * </pre>
     *
     * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
     */
    java.util.Map<java.lang.Integer, java.lang.Integer>
    getOfferInfoMap();
    /**
     * <pre>
     *出价信息
     * </pre>
     *
     * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
     */

    int getOfferInfoOrDefault(
        int key,
        int defaultValue);
    /**
     * <pre>
     *出价信息
     * </pre>
     *
     * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
     */

    int getOfferInfoOrThrow(
        int key);

    /**
     * <pre>
     *优先ID
     * </pre>
     *
     * <code>int32 firstIdx = 3;</code>
     */
    int getFirstIdx();

    /**
     * <pre>
     *偷取信息
     * </pre>
     *
     * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
     */
    int getStealInfoCount();
    /**
     * <pre>
     *偷取信息
     * </pre>
     *
     * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
     */
    boolean containsStealInfo(
        java.lang.String key);
    /**
     * Use {@link #getStealInfoMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getStealInfo();
    /**
     * <pre>
     *偷取信息
     * </pre>
     *
     * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getStealInfoMap();
    /**
     * <pre>
     *偷取信息
     * </pre>
     *
     * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
     */

    int getStealInfoOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <pre>
     *偷取信息
     * </pre>
     *
     * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
     */

    int getStealInfoOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code FarmMineDB}
   */
  public  static final class FarmMineDB extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FarmMineDB)
      FarmMineDBOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FarmMineDB.newBuilder() to construct.
    private FarmMineDB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FarmMineDB() {
      firstIdx_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FarmMineDB(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              protocol.FarmMine.FarmMineMyInfo.Builder subBuilder = null;
              if (myInfo_ != null) {
                subBuilder = myInfo_.toBuilder();
              }
              myInfo_ = input.readMessage(protocol.FarmMine.FarmMineMyInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(myInfo_);
                myInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                offerInfo_ = com.google.protobuf.MapField.newMapField(
                    OfferInfoDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000002;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
              offerInfo__ = input.readMessage(
                  OfferInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              offerInfo_.getMutableMap().put(
                  offerInfo__.getKey(), offerInfo__.getValue());
              break;
            }
            case 24: {

              firstIdx_ = input.readInt32();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                stealInfo_ = com.google.protobuf.MapField.newMapField(
                    StealInfoDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000008;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
              stealInfo__ = input.readMessage(
                  StealInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              stealInfo_.getMutableMap().put(
                  stealInfo__.getKey(), stealInfo__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.FarmMineDBOuterClass.internal_static_FarmMineDB_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 2:
          return internalGetOfferInfo();
        case 4:
          return internalGetStealInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.FarmMineDBOuterClass.internal_static_FarmMineDB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.FarmMineDBOuterClass.FarmMineDB.class, protocol.FarmMineDBOuterClass.FarmMineDB.Builder.class);
    }

    private int bitField0_;
    public static final int MYINFO_FIELD_NUMBER = 1;
    private protocol.FarmMine.FarmMineMyInfo myInfo_;
    /**
     * <code>.FarmMineMyInfo myInfo = 1;</code>
     */
    public boolean hasMyInfo() {
      return myInfo_ != null;
    }
    /**
     * <code>.FarmMineMyInfo myInfo = 1;</code>
     */
    public protocol.FarmMine.FarmMineMyInfo getMyInfo() {
      return myInfo_ == null ? protocol.FarmMine.FarmMineMyInfo.getDefaultInstance() : myInfo_;
    }
    /**
     * <code>.FarmMineMyInfo myInfo = 1;</code>
     */
    public protocol.FarmMine.FarmMineMyInfoOrBuilder getMyInfoOrBuilder() {
      return getMyInfo();
    }

    public static final int OFFERINFO_FIELD_NUMBER = 2;
    private static final class OfferInfoDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, java.lang.Integer>newDefaultInstance(
                  protocol.FarmMineDBOuterClass.internal_static_FarmMineDB_OfferInfoEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, java.lang.Integer> offerInfo_;
    private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
    internalGetOfferInfo() {
      if (offerInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            OfferInfoDefaultEntryHolder.defaultEntry);
      }
      return offerInfo_;
    }

    public int getOfferInfoCount() {
      return internalGetOfferInfo().getMap().size();
    }
    /**
     * <pre>
     *出价信息
     * </pre>
     *
     * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
     */

    public boolean containsOfferInfo(
        int key) {
      
      return internalGetOfferInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getOfferInfoMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, java.lang.Integer> getOfferInfo() {
      return getOfferInfoMap();
    }
    /**
     * <pre>
     *出价信息
     * </pre>
     *
     * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
     */

    public java.util.Map<java.lang.Integer, java.lang.Integer> getOfferInfoMap() {
      return internalGetOfferInfo().getMap();
    }
    /**
     * <pre>
     *出价信息
     * </pre>
     *
     * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
     */

    public int getOfferInfoOrDefault(
        int key,
        int defaultValue) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetOfferInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *出价信息
     * </pre>
     *
     * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
     */

    public int getOfferInfoOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, java.lang.Integer> map =
          internalGetOfferInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int FIRSTIDX_FIELD_NUMBER = 3;
    private int firstIdx_;
    /**
     * <pre>
     *优先ID
     * </pre>
     *
     * <code>int32 firstIdx = 3;</code>
     */
    public int getFirstIdx() {
      return firstIdx_;
    }

    public static final int STEALINFO_FIELD_NUMBER = 4;
    private static final class StealInfoDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  protocol.FarmMineDBOuterClass.internal_static_FarmMineDB_StealInfoEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0);
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> stealInfo_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetStealInfo() {
      if (stealInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StealInfoDefaultEntryHolder.defaultEntry);
      }
      return stealInfo_;
    }

    public int getStealInfoCount() {
      return internalGetStealInfo().getMap().size();
    }
    /**
     * <pre>
     *偷取信息
     * </pre>
     *
     * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
     */

    public boolean containsStealInfo(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetStealInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStealInfoMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer> getStealInfo() {
      return getStealInfoMap();
    }
    /**
     * <pre>
     *偷取信息
     * </pre>
     *
     * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
     */

    public java.util.Map<java.lang.String, java.lang.Integer> getStealInfoMap() {
      return internalGetStealInfo().getMap();
    }
    /**
     * <pre>
     *偷取信息
     * </pre>
     *
     * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
     */

    public int getStealInfoOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetStealInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *偷取信息
     * </pre>
     *
     * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
     */

    public int getStealInfoOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetStealInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (myInfo_ != null) {
        output.writeMessage(1, getMyInfo());
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetOfferInfo(),
          OfferInfoDefaultEntryHolder.defaultEntry,
          2);
      if (firstIdx_ != 0) {
        output.writeInt32(3, firstIdx_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetStealInfo(),
          StealInfoDefaultEntryHolder.defaultEntry,
          4);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (myInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMyInfo());
      }
      for (java.util.Map.Entry<java.lang.Integer, java.lang.Integer> entry
           : internalGetOfferInfo().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, java.lang.Integer>
        offerInfo__ = OfferInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, offerInfo__);
      }
      if (firstIdx_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, firstIdx_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetStealInfo().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        stealInfo__ = StealInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(4, stealInfo__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.FarmMineDBOuterClass.FarmMineDB)) {
        return super.equals(obj);
      }
      protocol.FarmMineDBOuterClass.FarmMineDB other = (protocol.FarmMineDBOuterClass.FarmMineDB) obj;

      boolean result = true;
      result = result && (hasMyInfo() == other.hasMyInfo());
      if (hasMyInfo()) {
        result = result && getMyInfo()
            .equals(other.getMyInfo());
      }
      result = result && internalGetOfferInfo().equals(
          other.internalGetOfferInfo());
      result = result && (getFirstIdx()
          == other.getFirstIdx());
      result = result && internalGetStealInfo().equals(
          other.internalGetStealInfo());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMyInfo()) {
        hash = (37 * hash) + MYINFO_FIELD_NUMBER;
        hash = (53 * hash) + getMyInfo().hashCode();
      }
      if (!internalGetOfferInfo().getMap().isEmpty()) {
        hash = (37 * hash) + OFFERINFO_FIELD_NUMBER;
        hash = (53 * hash) + internalGetOfferInfo().hashCode();
      }
      hash = (37 * hash) + FIRSTIDX_FIELD_NUMBER;
      hash = (53 * hash) + getFirstIdx();
      if (!internalGetStealInfo().getMap().isEmpty()) {
        hash = (37 * hash) + STEALINFO_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStealInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.FarmMineDBOuterClass.FarmMineDB parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.FarmMineDBOuterClass.FarmMineDB parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.FarmMineDBOuterClass.FarmMineDB parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.FarmMineDBOuterClass.FarmMineDB parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.FarmMineDBOuterClass.FarmMineDB parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.FarmMineDBOuterClass.FarmMineDB parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.FarmMineDBOuterClass.FarmMineDB parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.FarmMineDBOuterClass.FarmMineDB parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.FarmMineDBOuterClass.FarmMineDB parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.FarmMineDBOuterClass.FarmMineDB parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.FarmMineDBOuterClass.FarmMineDB parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.FarmMineDBOuterClass.FarmMineDB parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.FarmMineDBOuterClass.FarmMineDB prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FarmMineDB}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FarmMineDB)
        protocol.FarmMineDBOuterClass.FarmMineDBOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.FarmMineDBOuterClass.internal_static_FarmMineDB_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetOfferInfo();
          case 4:
            return internalGetStealInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableOfferInfo();
          case 4:
            return internalGetMutableStealInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.FarmMineDBOuterClass.internal_static_FarmMineDB_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.FarmMineDBOuterClass.FarmMineDB.class, protocol.FarmMineDBOuterClass.FarmMineDB.Builder.class);
      }

      // Construct using protocol.FarmMineDBOuterClass.FarmMineDB.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (myInfoBuilder_ == null) {
          myInfo_ = null;
        } else {
          myInfo_ = null;
          myInfoBuilder_ = null;
        }
        internalGetMutableOfferInfo().clear();
        firstIdx_ = 0;

        internalGetMutableStealInfo().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.FarmMineDBOuterClass.internal_static_FarmMineDB_descriptor;
      }

      public protocol.FarmMineDBOuterClass.FarmMineDB getDefaultInstanceForType() {
        return protocol.FarmMineDBOuterClass.FarmMineDB.getDefaultInstance();
      }

      public protocol.FarmMineDBOuterClass.FarmMineDB build() {
        protocol.FarmMineDBOuterClass.FarmMineDB result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.FarmMineDBOuterClass.FarmMineDB buildPartial() {
        protocol.FarmMineDBOuterClass.FarmMineDB result = new protocol.FarmMineDBOuterClass.FarmMineDB(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (myInfoBuilder_ == null) {
          result.myInfo_ = myInfo_;
        } else {
          result.myInfo_ = myInfoBuilder_.build();
        }
        result.offerInfo_ = internalGetOfferInfo();
        result.offerInfo_.makeImmutable();
        result.firstIdx_ = firstIdx_;
        result.stealInfo_ = internalGetStealInfo();
        result.stealInfo_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.FarmMineDBOuterClass.FarmMineDB) {
          return mergeFrom((protocol.FarmMineDBOuterClass.FarmMineDB)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.FarmMineDBOuterClass.FarmMineDB other) {
        if (other == protocol.FarmMineDBOuterClass.FarmMineDB.getDefaultInstance()) return this;
        if (other.hasMyInfo()) {
          mergeMyInfo(other.getMyInfo());
        }
        internalGetMutableOfferInfo().mergeFrom(
            other.internalGetOfferInfo());
        if (other.getFirstIdx() != 0) {
          setFirstIdx(other.getFirstIdx());
        }
        internalGetMutableStealInfo().mergeFrom(
            other.internalGetStealInfo());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.FarmMineDBOuterClass.FarmMineDB parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.FarmMineDBOuterClass.FarmMineDB) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private protocol.FarmMine.FarmMineMyInfo myInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.FarmMine.FarmMineMyInfo, protocol.FarmMine.FarmMineMyInfo.Builder, protocol.FarmMine.FarmMineMyInfoOrBuilder> myInfoBuilder_;
      /**
       * <code>.FarmMineMyInfo myInfo = 1;</code>
       */
      public boolean hasMyInfo() {
        return myInfoBuilder_ != null || myInfo_ != null;
      }
      /**
       * <code>.FarmMineMyInfo myInfo = 1;</code>
       */
      public protocol.FarmMine.FarmMineMyInfo getMyInfo() {
        if (myInfoBuilder_ == null) {
          return myInfo_ == null ? protocol.FarmMine.FarmMineMyInfo.getDefaultInstance() : myInfo_;
        } else {
          return myInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.FarmMineMyInfo myInfo = 1;</code>
       */
      public Builder setMyInfo(protocol.FarmMine.FarmMineMyInfo value) {
        if (myInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          myInfo_ = value;
          onChanged();
        } else {
          myInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.FarmMineMyInfo myInfo = 1;</code>
       */
      public Builder setMyInfo(
          protocol.FarmMine.FarmMineMyInfo.Builder builderForValue) {
        if (myInfoBuilder_ == null) {
          myInfo_ = builderForValue.build();
          onChanged();
        } else {
          myInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.FarmMineMyInfo myInfo = 1;</code>
       */
      public Builder mergeMyInfo(protocol.FarmMine.FarmMineMyInfo value) {
        if (myInfoBuilder_ == null) {
          if (myInfo_ != null) {
            myInfo_ =
              protocol.FarmMine.FarmMineMyInfo.newBuilder(myInfo_).mergeFrom(value).buildPartial();
          } else {
            myInfo_ = value;
          }
          onChanged();
        } else {
          myInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.FarmMineMyInfo myInfo = 1;</code>
       */
      public Builder clearMyInfo() {
        if (myInfoBuilder_ == null) {
          myInfo_ = null;
          onChanged();
        } else {
          myInfo_ = null;
          myInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.FarmMineMyInfo myInfo = 1;</code>
       */
      public protocol.FarmMine.FarmMineMyInfo.Builder getMyInfoBuilder() {
        
        onChanged();
        return getMyInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.FarmMineMyInfo myInfo = 1;</code>
       */
      public protocol.FarmMine.FarmMineMyInfoOrBuilder getMyInfoOrBuilder() {
        if (myInfoBuilder_ != null) {
          return myInfoBuilder_.getMessageOrBuilder();
        } else {
          return myInfo_ == null ?
              protocol.FarmMine.FarmMineMyInfo.getDefaultInstance() : myInfo_;
        }
      }
      /**
       * <code>.FarmMineMyInfo myInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          protocol.FarmMine.FarmMineMyInfo, protocol.FarmMine.FarmMineMyInfo.Builder, protocol.FarmMine.FarmMineMyInfoOrBuilder> 
          getMyInfoFieldBuilder() {
        if (myInfoBuilder_ == null) {
          myInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              protocol.FarmMine.FarmMineMyInfo, protocol.FarmMine.FarmMineMyInfo.Builder, protocol.FarmMine.FarmMineMyInfoOrBuilder>(
                  getMyInfo(),
                  getParentForChildren(),
                  isClean());
          myInfo_ = null;
        }
        return myInfoBuilder_;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, java.lang.Integer> offerInfo_;
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
      internalGetOfferInfo() {
        if (offerInfo_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              OfferInfoDefaultEntryHolder.defaultEntry);
        }
        return offerInfo_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, java.lang.Integer>
      internalGetMutableOfferInfo() {
        onChanged();;
        if (offerInfo_ == null) {
          offerInfo_ = com.google.protobuf.MapField.newMapField(
              OfferInfoDefaultEntryHolder.defaultEntry);
        }
        if (!offerInfo_.isMutable()) {
          offerInfo_ = offerInfo_.copy();
        }
        return offerInfo_;
      }

      public int getOfferInfoCount() {
        return internalGetOfferInfo().getMap().size();
      }
      /**
       * <pre>
       *出价信息
       * </pre>
       *
       * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
       */

      public boolean containsOfferInfo(
          int key) {
        
        return internalGetOfferInfo().getMap().containsKey(key);
      }
      /**
       * Use {@link #getOfferInfoMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Integer> getOfferInfo() {
        return getOfferInfoMap();
      }
      /**
       * <pre>
       *出价信息
       * </pre>
       *
       * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
       */

      public java.util.Map<java.lang.Integer, java.lang.Integer> getOfferInfoMap() {
        return internalGetOfferInfo().getMap();
      }
      /**
       * <pre>
       *出价信息
       * </pre>
       *
       * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
       */

      public int getOfferInfoOrDefault(
          int key,
          int defaultValue) {
        
        java.util.Map<java.lang.Integer, java.lang.Integer> map =
            internalGetOfferInfo().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *出价信息
       * </pre>
       *
       * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
       */

      public int getOfferInfoOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, java.lang.Integer> map =
            internalGetOfferInfo().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearOfferInfo() {
        internalGetMutableOfferInfo().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *出价信息
       * </pre>
       *
       * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
       */

      public Builder removeOfferInfo(
          int key) {
        
        internalGetMutableOfferInfo().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, java.lang.Integer>
      getMutableOfferInfo() {
        return internalGetMutableOfferInfo().getMutableMap();
      }
      /**
       * <pre>
       *出价信息
       * </pre>
       *
       * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
       */
      public Builder putOfferInfo(
          int key,
          int value) {
        
        
        internalGetMutableOfferInfo().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *出价信息
       * </pre>
       *
       * <code>map&lt;int32, int32&gt; offerInfo = 2;</code>
       */

      public Builder putAllOfferInfo(
          java.util.Map<java.lang.Integer, java.lang.Integer> values) {
        internalGetMutableOfferInfo().getMutableMap()
            .putAll(values);
        return this;
      }

      private int firstIdx_ ;
      /**
       * <pre>
       *优先ID
       * </pre>
       *
       * <code>int32 firstIdx = 3;</code>
       */
      public int getFirstIdx() {
        return firstIdx_;
      }
      /**
       * <pre>
       *优先ID
       * </pre>
       *
       * <code>int32 firstIdx = 3;</code>
       */
      public Builder setFirstIdx(int value) {
        
        firstIdx_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *优先ID
       * </pre>
       *
       * <code>int32 firstIdx = 3;</code>
       */
      public Builder clearFirstIdx() {
        
        firstIdx_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> stealInfo_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetStealInfo() {
        if (stealInfo_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StealInfoDefaultEntryHolder.defaultEntry);
        }
        return stealInfo_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
      internalGetMutableStealInfo() {
        onChanged();;
        if (stealInfo_ == null) {
          stealInfo_ = com.google.protobuf.MapField.newMapField(
              StealInfoDefaultEntryHolder.defaultEntry);
        }
        if (!stealInfo_.isMutable()) {
          stealInfo_ = stealInfo_.copy();
        }
        return stealInfo_;
      }

      public int getStealInfoCount() {
        return internalGetStealInfo().getMap().size();
      }
      /**
       * <pre>
       *偷取信息
       * </pre>
       *
       * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
       */

      public boolean containsStealInfo(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetStealInfo().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStealInfoMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer> getStealInfo() {
        return getStealInfoMap();
      }
      /**
       * <pre>
       *偷取信息
       * </pre>
       *
       * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
       */

      public java.util.Map<java.lang.String, java.lang.Integer> getStealInfoMap() {
        return internalGetStealInfo().getMap();
      }
      /**
       * <pre>
       *偷取信息
       * </pre>
       *
       * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
       */

      public int getStealInfoOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetStealInfo().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *偷取信息
       * </pre>
       *
       * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
       */

      public int getStealInfoOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetStealInfo().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearStealInfo() {
        internalGetMutableStealInfo().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *偷取信息
       * </pre>
       *
       * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
       */

      public Builder removeStealInfo(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableStealInfo().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getMutableStealInfo() {
        return internalGetMutableStealInfo().getMutableMap();
      }
      /**
       * <pre>
       *偷取信息
       * </pre>
       *
       * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
       */
      public Builder putStealInfo(
          java.lang.String key,
          int value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        
        internalGetMutableStealInfo().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *偷取信息
       * </pre>
       *
       * <code>map&lt;string, int32&gt; stealInfo = 4;</code>
       */

      public Builder putAllStealInfo(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        internalGetMutableStealInfo().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FarmMineDB)
    }

    // @@protoc_insertion_point(class_scope:FarmMineDB)
    private static final protocol.FarmMineDBOuterClass.FarmMineDB DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.FarmMineDBOuterClass.FarmMineDB();
    }

    public static protocol.FarmMineDBOuterClass.FarmMineDB getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FarmMineDB>
        PARSER = new com.google.protobuf.AbstractParser<FarmMineDB>() {
      public FarmMineDB parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FarmMineDB(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FarmMineDB> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FarmMineDB> getParserForType() {
      return PARSER;
    }

    public protocol.FarmMineDBOuterClass.FarmMineDB getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FarmMineDB_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FarmMineDB_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FarmMineDB_OfferInfoEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FarmMineDB_OfferInfoEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FarmMineDB_StealInfoEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FarmMineDB_StealInfoEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020FarmMineDB.proto\032\016FarmMine.proto\"\201\002\n\nF" +
      "armMineDB\022\037\n\006myInfo\030\001 \001(\0132\017.FarmMineMyIn" +
      "fo\022-\n\tofferInfo\030\002 \003(\0132\032.FarmMineDB.Offer" +
      "InfoEntry\022\020\n\010firstIdx\030\003 \001(\005\022-\n\tstealInfo" +
      "\030\004 \003(\0132\032.FarmMineDB.StealInfoEntry\0320\n\016Of" +
      "ferInfoEntry\022\013\n\003key\030\001 \001(\005\022\r\n\005value\030\002 \001(\005" +
      ":\0028\001\0320\n\016StealInfoEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005v" +
      "alue\030\002 \001(\005:\0028\001B\033\n\010protocol\252\002\016ETHotfix.Pr" +
      "otob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.FarmMine.getDescriptor(),
        }, assigner);
    internal_static_FarmMineDB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FarmMineDB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FarmMineDB_descriptor,
        new java.lang.String[] { "MyInfo", "OfferInfo", "FirstIdx", "StealInfo", });
    internal_static_FarmMineDB_OfferInfoEntry_descriptor =
      internal_static_FarmMineDB_descriptor.getNestedTypes().get(0);
    internal_static_FarmMineDB_OfferInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FarmMineDB_OfferInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_FarmMineDB_StealInfoEntry_descriptor =
      internal_static_FarmMineDB_descriptor.getNestedTypes().get(1);
    internal_static_FarmMineDB_StealInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FarmMineDB_StealInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    protocol.FarmMine.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
