// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ShopDB.proto

package protocol;

public final class ShopDB {
  private ShopDB() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DB_ShopOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DB_Shop)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
     * </pre>
     *
     * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
     */
    int getShopInfoCount();
    /**
     * <pre>
     *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
     * </pre>
     *
     * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
     */
    boolean containsShopInfo(
        int key);
    /**
     * Use {@link #getShopInfoMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo>
    getShopInfo();
    /**
     * <pre>
     *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
     * </pre>
     *
     * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
     */
    java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo>
    getShopInfoMap();
    /**
     * <pre>
     *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
     * </pre>
     *
     * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
     */

    protocol.ShopDB.PlayerShopInfo getShopInfoOrDefault(
        int key,
        protocol.ShopDB.PlayerShopInfo defaultValue);
    /**
     * <pre>
     *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
     * </pre>
     *
     * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
     */

    protocol.ShopDB.PlayerShopInfo getShopInfoOrThrow(
        int key);
  }
  /**
   * Protobuf type {@code DB_Shop}
   */
  public  static final class DB_Shop extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DB_Shop)
      DB_ShopOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DB_Shop.newBuilder() to construct.
    private DB_Shop(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DB_Shop() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DB_Shop(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                shopInfo_ = com.google.protobuf.MapField.newMapField(
                    ShopInfoDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, protocol.ShopDB.PlayerShopInfo>
              shopInfo__ = input.readMessage(
                  ShopInfoDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              shopInfo_.getMutableMap().put(
                  shopInfo__.getKey(), shopInfo__.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ShopDB.internal_static_DB_Shop_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetShopInfo();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ShopDB.internal_static_DB_Shop_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ShopDB.DB_Shop.class, protocol.ShopDB.DB_Shop.Builder.class);
    }

    public static final int SHOPINFO_FIELD_NUMBER = 1;
    private static final class ShopInfoDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, protocol.ShopDB.PlayerShopInfo> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, protocol.ShopDB.PlayerShopInfo>newDefaultInstance(
                  protocol.ShopDB.internal_static_DB_Shop_ShopInfoEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  protocol.ShopDB.PlayerShopInfo.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, protocol.ShopDB.PlayerShopInfo> shopInfo_;
    private com.google.protobuf.MapField<java.lang.Integer, protocol.ShopDB.PlayerShopInfo>
    internalGetShopInfo() {
      if (shopInfo_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ShopInfoDefaultEntryHolder.defaultEntry);
      }
      return shopInfo_;
    }

    public int getShopInfoCount() {
      return internalGetShopInfo().getMap().size();
    }
    /**
     * <pre>
     *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
     * </pre>
     *
     * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
     */

    public boolean containsShopInfo(
        int key) {
      
      return internalGetShopInfo().getMap().containsKey(key);
    }
    /**
     * Use {@link #getShopInfoMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo> getShopInfo() {
      return getShopInfoMap();
    }
    /**
     * <pre>
     *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
     * </pre>
     *
     * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
     */

    public java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo> getShopInfoMap() {
      return internalGetShopInfo().getMap();
    }
    /**
     * <pre>
     *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
     * </pre>
     *
     * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
     */

    public protocol.ShopDB.PlayerShopInfo getShopInfoOrDefault(
        int key,
        protocol.ShopDB.PlayerShopInfo defaultValue) {
      
      java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo> map =
          internalGetShopInfo().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
     * </pre>
     *
     * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
     */

    public protocol.ShopDB.PlayerShopInfo getShopInfoOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo> map =
          internalGetShopInfo().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetShopInfo(),
          ShopInfoDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.Integer, protocol.ShopDB.PlayerShopInfo> entry
           : internalGetShopInfo().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, protocol.ShopDB.PlayerShopInfo>
        shopInfo__ = ShopInfoDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, shopInfo__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.ShopDB.DB_Shop)) {
        return super.equals(obj);
      }
      protocol.ShopDB.DB_Shop other = (protocol.ShopDB.DB_Shop) obj;

      boolean result = true;
      result = result && internalGetShopInfo().equals(
          other.internalGetShopInfo());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetShopInfo().getMap().isEmpty()) {
        hash = (37 * hash) + SHOPINFO_FIELD_NUMBER;
        hash = (53 * hash) + internalGetShopInfo().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.ShopDB.DB_Shop parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShopDB.DB_Shop parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShopDB.DB_Shop parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShopDB.DB_Shop parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShopDB.DB_Shop parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShopDB.DB_Shop parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShopDB.DB_Shop parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ShopDB.DB_Shop parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ShopDB.DB_Shop parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.ShopDB.DB_Shop parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ShopDB.DB_Shop parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ShopDB.DB_Shop parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.ShopDB.DB_Shop prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DB_Shop}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DB_Shop)
        protocol.ShopDB.DB_ShopOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ShopDB.internal_static_DB_Shop_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetShopInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableShopInfo();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ShopDB.internal_static_DB_Shop_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ShopDB.DB_Shop.class, protocol.ShopDB.DB_Shop.Builder.class);
      }

      // Construct using protocol.ShopDB.DB_Shop.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        internalGetMutableShopInfo().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ShopDB.internal_static_DB_Shop_descriptor;
      }

      public protocol.ShopDB.DB_Shop getDefaultInstanceForType() {
        return protocol.ShopDB.DB_Shop.getDefaultInstance();
      }

      public protocol.ShopDB.DB_Shop build() {
        protocol.ShopDB.DB_Shop result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.ShopDB.DB_Shop buildPartial() {
        protocol.ShopDB.DB_Shop result = new protocol.ShopDB.DB_Shop(this);
        int from_bitField0_ = bitField0_;
        result.shopInfo_ = internalGetShopInfo();
        result.shopInfo_.makeImmutable();
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ShopDB.DB_Shop) {
          return mergeFrom((protocol.ShopDB.DB_Shop)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ShopDB.DB_Shop other) {
        if (other == protocol.ShopDB.DB_Shop.getDefaultInstance()) return this;
        internalGetMutableShopInfo().mergeFrom(
            other.internalGetShopInfo());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.ShopDB.DB_Shop parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.ShopDB.DB_Shop) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.Integer, protocol.ShopDB.PlayerShopInfo> shopInfo_;
      private com.google.protobuf.MapField<java.lang.Integer, protocol.ShopDB.PlayerShopInfo>
      internalGetShopInfo() {
        if (shopInfo_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ShopInfoDefaultEntryHolder.defaultEntry);
        }
        return shopInfo_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, protocol.ShopDB.PlayerShopInfo>
      internalGetMutableShopInfo() {
        onChanged();;
        if (shopInfo_ == null) {
          shopInfo_ = com.google.protobuf.MapField.newMapField(
              ShopInfoDefaultEntryHolder.defaultEntry);
        }
        if (!shopInfo_.isMutable()) {
          shopInfo_ = shopInfo_.copy();
        }
        return shopInfo_;
      }

      public int getShopInfoCount() {
        return internalGetShopInfo().getMap().size();
      }
      /**
       * <pre>
       *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
       * </pre>
       *
       * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
       */

      public boolean containsShopInfo(
          int key) {
        
        return internalGetShopInfo().getMap().containsKey(key);
      }
      /**
       * Use {@link #getShopInfoMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo> getShopInfo() {
        return getShopInfoMap();
      }
      /**
       * <pre>
       *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
       * </pre>
       *
       * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
       */

      public java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo> getShopInfoMap() {
        return internalGetShopInfo().getMap();
      }
      /**
       * <pre>
       *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
       * </pre>
       *
       * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
       */

      public protocol.ShopDB.PlayerShopInfo getShopInfoOrDefault(
          int key,
          protocol.ShopDB.PlayerShopInfo defaultValue) {
        
        java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo> map =
            internalGetShopInfo().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
       * </pre>
       *
       * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
       */

      public protocol.ShopDB.PlayerShopInfo getShopInfoOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo> map =
            internalGetShopInfo().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearShopInfo() {
        internalGetMutableShopInfo().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
       * </pre>
       *
       * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
       */

      public Builder removeShopInfo(
          int key) {
        
        internalGetMutableShopInfo().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo>
      getMutableShopInfo() {
        return internalGetMutableShopInfo().getMutableMap();
      }
      /**
       * <pre>
       *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
       * </pre>
       *
       * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
       */
      public Builder putShopInfo(
          int key,
          protocol.ShopDB.PlayerShopInfo value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableShopInfo().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *用于保存玩家商店信息&lt;ShopTypeEnum_Value,&gt;
       * </pre>
       *
       * <code>map&lt;int32, .PlayerShopInfo&gt; shopInfo = 1;</code>
       */

      public Builder putAllShopInfo(
          java.util.Map<java.lang.Integer, protocol.ShopDB.PlayerShopInfo> values) {
        internalGetMutableShopInfo().getMutableMap()
            .putAll(values);
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DB_Shop)
    }

    // @@protoc_insertion_point(class_scope:DB_Shop)
    private static final protocol.ShopDB.DB_Shop DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.ShopDB.DB_Shop();
    }

    public static protocol.ShopDB.DB_Shop getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DB_Shop>
        PARSER = new com.google.protobuf.AbstractParser<DB_Shop>() {
      public DB_Shop parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DB_Shop(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DB_Shop> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DB_Shop> getParserForType() {
      return PARSER;
    }

    public protocol.ShopDB.DB_Shop getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PlayerShopInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerShopInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *下次自动刷新时间
     * </pre>
     *
     * <code>int64 nextRefreshTime = 1;</code>
     */
    long getNextRefreshTime();

    /**
     * <pre>
     *手动刷新次数
     * </pre>
     *
     * <code>int32 manualRefreshTimes = 2;</code>
     */
    int getManualRefreshTimes();

    /**
     * <pre>
     *购买记录
     * </pre>
     *
     * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
     */
    int getBuyRecordCount();
    /**
     * <pre>
     *购买记录
     * </pre>
     *
     * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
     */
    boolean containsBuyRecord(
        int key);
    /**
     * Use {@link #getBuyRecordMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo>
    getBuyRecord();
    /**
     * <pre>
     *购买记录
     * </pre>
     *
     * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
     */
    java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo>
    getBuyRecordMap();
    /**
     * <pre>
     *购买记录
     * </pre>
     *
     * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
     */

    protocol.Shop.GoodsInfo getBuyRecordOrDefault(
        int key,
        protocol.Shop.GoodsInfo defaultValue);
    /**
     * <pre>
     *购买记录
     * </pre>
     *
     * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
     */

    protocol.Shop.GoodsInfo getBuyRecordOrThrow(
        int key);

    /**
     * <pre>
     *自动刷新次数
     * </pre>
     *
     * <code>int32 autoRefreshTimes = 4;</code>
     */
    int getAutoRefreshTimes();

    /**
     * <pre>
     *完成任务id
     * </pre>
     *
     * <code>repeated int32 completeMissionId = 5;</code>
     */
    java.util.List<java.lang.Integer> getCompleteMissionIdList();
    /**
     * <pre>
     *完成任务id
     * </pre>
     *
     * <code>repeated int32 completeMissionId = 5;</code>
     */
    int getCompleteMissionIdCount();
    /**
     * <pre>
     *完成任务id
     * </pre>
     *
     * <code>repeated int32 completeMissionId = 5;</code>
     */
    int getCompleteMissionId(int index);
  }
  /**
   * Protobuf type {@code PlayerShopInfo}
   */
  public  static final class PlayerShopInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerShopInfo)
      PlayerShopInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerShopInfo.newBuilder() to construct.
    private PlayerShopInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerShopInfo() {
      nextRefreshTime_ = 0L;
      manualRefreshTimes_ = 0;
      autoRefreshTimes_ = 0;
      completeMissionId_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerShopInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              nextRefreshTime_ = input.readInt64();
              break;
            }
            case 16: {

              manualRefreshTimes_ = input.readInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                buyRecord_ = com.google.protobuf.MapField.newMapField(
                    BuyRecordDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.Integer, protocol.Shop.GoodsInfo>
              buyRecord__ = input.readMessage(
                  BuyRecordDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              buyRecord_.getMutableMap().put(
                  buyRecord__.getKey(), buyRecord__.getValue());
              break;
            }
            case 32: {

              autoRefreshTimes_ = input.readInt32();
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                completeMissionId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              completeMissionId_.add(input.readInt32());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                completeMissionId_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                completeMissionId_.add(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          completeMissionId_ = java.util.Collections.unmodifiableList(completeMissionId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return protocol.ShopDB.internal_static_PlayerShopInfo_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetBuyRecord();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return protocol.ShopDB.internal_static_PlayerShopInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              protocol.ShopDB.PlayerShopInfo.class, protocol.ShopDB.PlayerShopInfo.Builder.class);
    }

    private int bitField0_;
    public static final int NEXTREFRESHTIME_FIELD_NUMBER = 1;
    private long nextRefreshTime_;
    /**
     * <pre>
     *下次自动刷新时间
     * </pre>
     *
     * <code>int64 nextRefreshTime = 1;</code>
     */
    public long getNextRefreshTime() {
      return nextRefreshTime_;
    }

    public static final int MANUALREFRESHTIMES_FIELD_NUMBER = 2;
    private int manualRefreshTimes_;
    /**
     * <pre>
     *手动刷新次数
     * </pre>
     *
     * <code>int32 manualRefreshTimes = 2;</code>
     */
    public int getManualRefreshTimes() {
      return manualRefreshTimes_;
    }

    public static final int BUYRECORD_FIELD_NUMBER = 3;
    private static final class BuyRecordDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.Integer, protocol.Shop.GoodsInfo> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.Integer, protocol.Shop.GoodsInfo>newDefaultInstance(
                  protocol.ShopDB.internal_static_PlayerShopInfo_BuyRecordEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.INT32,
                  0,
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  protocol.Shop.GoodsInfo.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        java.lang.Integer, protocol.Shop.GoodsInfo> buyRecord_;
    private com.google.protobuf.MapField<java.lang.Integer, protocol.Shop.GoodsInfo>
    internalGetBuyRecord() {
      if (buyRecord_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            BuyRecordDefaultEntryHolder.defaultEntry);
      }
      return buyRecord_;
    }

    public int getBuyRecordCount() {
      return internalGetBuyRecord().getMap().size();
    }
    /**
     * <pre>
     *购买记录
     * </pre>
     *
     * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
     */

    public boolean containsBuyRecord(
        int key) {
      
      return internalGetBuyRecord().getMap().containsKey(key);
    }
    /**
     * Use {@link #getBuyRecordMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo> getBuyRecord() {
      return getBuyRecordMap();
    }
    /**
     * <pre>
     *购买记录
     * </pre>
     *
     * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
     */

    public java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo> getBuyRecordMap() {
      return internalGetBuyRecord().getMap();
    }
    /**
     * <pre>
     *购买记录
     * </pre>
     *
     * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
     */

    public protocol.Shop.GoodsInfo getBuyRecordOrDefault(
        int key,
        protocol.Shop.GoodsInfo defaultValue) {
      
      java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo> map =
          internalGetBuyRecord().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     *购买记录
     * </pre>
     *
     * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
     */

    public protocol.Shop.GoodsInfo getBuyRecordOrThrow(
        int key) {
      
      java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo> map =
          internalGetBuyRecord().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int AUTOREFRESHTIMES_FIELD_NUMBER = 4;
    private int autoRefreshTimes_;
    /**
     * <pre>
     *自动刷新次数
     * </pre>
     *
     * <code>int32 autoRefreshTimes = 4;</code>
     */
    public int getAutoRefreshTimes() {
      return autoRefreshTimes_;
    }

    public static final int COMPLETEMISSIONID_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Integer> completeMissionId_;
    /**
     * <pre>
     *完成任务id
     * </pre>
     *
     * <code>repeated int32 completeMissionId = 5;</code>
     */
    public java.util.List<java.lang.Integer>
        getCompleteMissionIdList() {
      return completeMissionId_;
    }
    /**
     * <pre>
     *完成任务id
     * </pre>
     *
     * <code>repeated int32 completeMissionId = 5;</code>
     */
    public int getCompleteMissionIdCount() {
      return completeMissionId_.size();
    }
    /**
     * <pre>
     *完成任务id
     * </pre>
     *
     * <code>repeated int32 completeMissionId = 5;</code>
     */
    public int getCompleteMissionId(int index) {
      return completeMissionId_.get(index);
    }
    private int completeMissionIdMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (nextRefreshTime_ != 0L) {
        output.writeInt64(1, nextRefreshTime_);
      }
      if (manualRefreshTimes_ != 0) {
        output.writeInt32(2, manualRefreshTimes_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeIntegerMapTo(
          output,
          internalGetBuyRecord(),
          BuyRecordDefaultEntryHolder.defaultEntry,
          3);
      if (autoRefreshTimes_ != 0) {
        output.writeInt32(4, autoRefreshTimes_);
      }
      if (getCompleteMissionIdList().size() > 0) {
        output.writeUInt32NoTag(42);
        output.writeUInt32NoTag(completeMissionIdMemoizedSerializedSize);
      }
      for (int i = 0; i < completeMissionId_.size(); i++) {
        output.writeInt32NoTag(completeMissionId_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (nextRefreshTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, nextRefreshTime_);
      }
      if (manualRefreshTimes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, manualRefreshTimes_);
      }
      for (java.util.Map.Entry<java.lang.Integer, protocol.Shop.GoodsInfo> entry
           : internalGetBuyRecord().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.Integer, protocol.Shop.GoodsInfo>
        buyRecord__ = BuyRecordDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, buyRecord__);
      }
      if (autoRefreshTimes_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, autoRefreshTimes_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < completeMissionId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(completeMissionId_.get(i));
        }
        size += dataSize;
        if (!getCompleteMissionIdList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        completeMissionIdMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof protocol.ShopDB.PlayerShopInfo)) {
        return super.equals(obj);
      }
      protocol.ShopDB.PlayerShopInfo other = (protocol.ShopDB.PlayerShopInfo) obj;

      boolean result = true;
      result = result && (getNextRefreshTime()
          == other.getNextRefreshTime());
      result = result && (getManualRefreshTimes()
          == other.getManualRefreshTimes());
      result = result && internalGetBuyRecord().equals(
          other.internalGetBuyRecord());
      result = result && (getAutoRefreshTimes()
          == other.getAutoRefreshTimes());
      result = result && getCompleteMissionIdList()
          .equals(other.getCompleteMissionIdList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NEXTREFRESHTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getNextRefreshTime());
      hash = (37 * hash) + MANUALREFRESHTIMES_FIELD_NUMBER;
      hash = (53 * hash) + getManualRefreshTimes();
      if (!internalGetBuyRecord().getMap().isEmpty()) {
        hash = (37 * hash) + BUYRECORD_FIELD_NUMBER;
        hash = (53 * hash) + internalGetBuyRecord().hashCode();
      }
      hash = (37 * hash) + AUTOREFRESHTIMES_FIELD_NUMBER;
      hash = (53 * hash) + getAutoRefreshTimes();
      if (getCompleteMissionIdCount() > 0) {
        hash = (37 * hash) + COMPLETEMISSIONID_FIELD_NUMBER;
        hash = (53 * hash) + getCompleteMissionIdList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static protocol.ShopDB.PlayerShopInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShopDB.PlayerShopInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShopDB.PlayerShopInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShopDB.PlayerShopInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShopDB.PlayerShopInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static protocol.ShopDB.PlayerShopInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static protocol.ShopDB.PlayerShopInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ShopDB.PlayerShopInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ShopDB.PlayerShopInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static protocol.ShopDB.PlayerShopInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static protocol.ShopDB.PlayerShopInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static protocol.ShopDB.PlayerShopInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(protocol.ShopDB.PlayerShopInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerShopInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerShopInfo)
        protocol.ShopDB.PlayerShopInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return protocol.ShopDB.internal_static_PlayerShopInfo_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetBuyRecord();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableBuyRecord();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return protocol.ShopDB.internal_static_PlayerShopInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                protocol.ShopDB.PlayerShopInfo.class, protocol.ShopDB.PlayerShopInfo.Builder.class);
      }

      // Construct using protocol.ShopDB.PlayerShopInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        nextRefreshTime_ = 0L;

        manualRefreshTimes_ = 0;

        internalGetMutableBuyRecord().clear();
        autoRefreshTimes_ = 0;

        completeMissionId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return protocol.ShopDB.internal_static_PlayerShopInfo_descriptor;
      }

      public protocol.ShopDB.PlayerShopInfo getDefaultInstanceForType() {
        return protocol.ShopDB.PlayerShopInfo.getDefaultInstance();
      }

      public protocol.ShopDB.PlayerShopInfo build() {
        protocol.ShopDB.PlayerShopInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public protocol.ShopDB.PlayerShopInfo buildPartial() {
        protocol.ShopDB.PlayerShopInfo result = new protocol.ShopDB.PlayerShopInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.nextRefreshTime_ = nextRefreshTime_;
        result.manualRefreshTimes_ = manualRefreshTimes_;
        result.buyRecord_ = internalGetBuyRecord();
        result.buyRecord_.makeImmutable();
        result.autoRefreshTimes_ = autoRefreshTimes_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          completeMissionId_ = java.util.Collections.unmodifiableList(completeMissionId_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.completeMissionId_ = completeMissionId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof protocol.ShopDB.PlayerShopInfo) {
          return mergeFrom((protocol.ShopDB.PlayerShopInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(protocol.ShopDB.PlayerShopInfo other) {
        if (other == protocol.ShopDB.PlayerShopInfo.getDefaultInstance()) return this;
        if (other.getNextRefreshTime() != 0L) {
          setNextRefreshTime(other.getNextRefreshTime());
        }
        if (other.getManualRefreshTimes() != 0) {
          setManualRefreshTimes(other.getManualRefreshTimes());
        }
        internalGetMutableBuyRecord().mergeFrom(
            other.internalGetBuyRecord());
        if (other.getAutoRefreshTimes() != 0) {
          setAutoRefreshTimes(other.getAutoRefreshTimes());
        }
        if (!other.completeMissionId_.isEmpty()) {
          if (completeMissionId_.isEmpty()) {
            completeMissionId_ = other.completeMissionId_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureCompleteMissionIdIsMutable();
            completeMissionId_.addAll(other.completeMissionId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        protocol.ShopDB.PlayerShopInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (protocol.ShopDB.PlayerShopInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long nextRefreshTime_ ;
      /**
       * <pre>
       *下次自动刷新时间
       * </pre>
       *
       * <code>int64 nextRefreshTime = 1;</code>
       */
      public long getNextRefreshTime() {
        return nextRefreshTime_;
      }
      /**
       * <pre>
       *下次自动刷新时间
       * </pre>
       *
       * <code>int64 nextRefreshTime = 1;</code>
       */
      public Builder setNextRefreshTime(long value) {
        
        nextRefreshTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *下次自动刷新时间
       * </pre>
       *
       * <code>int64 nextRefreshTime = 1;</code>
       */
      public Builder clearNextRefreshTime() {
        
        nextRefreshTime_ = 0L;
        onChanged();
        return this;
      }

      private int manualRefreshTimes_ ;
      /**
       * <pre>
       *手动刷新次数
       * </pre>
       *
       * <code>int32 manualRefreshTimes = 2;</code>
       */
      public int getManualRefreshTimes() {
        return manualRefreshTimes_;
      }
      /**
       * <pre>
       *手动刷新次数
       * </pre>
       *
       * <code>int32 manualRefreshTimes = 2;</code>
       */
      public Builder setManualRefreshTimes(int value) {
        
        manualRefreshTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *手动刷新次数
       * </pre>
       *
       * <code>int32 manualRefreshTimes = 2;</code>
       */
      public Builder clearManualRefreshTimes() {
        
        manualRefreshTimes_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.Integer, protocol.Shop.GoodsInfo> buyRecord_;
      private com.google.protobuf.MapField<java.lang.Integer, protocol.Shop.GoodsInfo>
      internalGetBuyRecord() {
        if (buyRecord_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              BuyRecordDefaultEntryHolder.defaultEntry);
        }
        return buyRecord_;
      }
      private com.google.protobuf.MapField<java.lang.Integer, protocol.Shop.GoodsInfo>
      internalGetMutableBuyRecord() {
        onChanged();;
        if (buyRecord_ == null) {
          buyRecord_ = com.google.protobuf.MapField.newMapField(
              BuyRecordDefaultEntryHolder.defaultEntry);
        }
        if (!buyRecord_.isMutable()) {
          buyRecord_ = buyRecord_.copy();
        }
        return buyRecord_;
      }

      public int getBuyRecordCount() {
        return internalGetBuyRecord().getMap().size();
      }
      /**
       * <pre>
       *购买记录
       * </pre>
       *
       * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
       */

      public boolean containsBuyRecord(
          int key) {
        
        return internalGetBuyRecord().getMap().containsKey(key);
      }
      /**
       * Use {@link #getBuyRecordMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo> getBuyRecord() {
        return getBuyRecordMap();
      }
      /**
       * <pre>
       *购买记录
       * </pre>
       *
       * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
       */

      public java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo> getBuyRecordMap() {
        return internalGetBuyRecord().getMap();
      }
      /**
       * <pre>
       *购买记录
       * </pre>
       *
       * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
       */

      public protocol.Shop.GoodsInfo getBuyRecordOrDefault(
          int key,
          protocol.Shop.GoodsInfo defaultValue) {
        
        java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo> map =
            internalGetBuyRecord().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <pre>
       *购买记录
       * </pre>
       *
       * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
       */

      public protocol.Shop.GoodsInfo getBuyRecordOrThrow(
          int key) {
        
        java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo> map =
            internalGetBuyRecord().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearBuyRecord() {
        internalGetMutableBuyRecord().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <pre>
       *购买记录
       * </pre>
       *
       * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
       */

      public Builder removeBuyRecord(
          int key) {
        
        internalGetMutableBuyRecord().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo>
      getMutableBuyRecord() {
        return internalGetMutableBuyRecord().getMutableMap();
      }
      /**
       * <pre>
       *购买记录
       * </pre>
       *
       * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
       */
      public Builder putBuyRecord(
          int key,
          protocol.Shop.GoodsInfo value) {
        
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableBuyRecord().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <pre>
       *购买记录
       * </pre>
       *
       * <code>map&lt;int32, .GoodsInfo&gt; buyRecord = 3;</code>
       */

      public Builder putAllBuyRecord(
          java.util.Map<java.lang.Integer, protocol.Shop.GoodsInfo> values) {
        internalGetMutableBuyRecord().getMutableMap()
            .putAll(values);
        return this;
      }

      private int autoRefreshTimes_ ;
      /**
       * <pre>
       *自动刷新次数
       * </pre>
       *
       * <code>int32 autoRefreshTimes = 4;</code>
       */
      public int getAutoRefreshTimes() {
        return autoRefreshTimes_;
      }
      /**
       * <pre>
       *自动刷新次数
       * </pre>
       *
       * <code>int32 autoRefreshTimes = 4;</code>
       */
      public Builder setAutoRefreshTimes(int value) {
        
        autoRefreshTimes_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *自动刷新次数
       * </pre>
       *
       * <code>int32 autoRefreshTimes = 4;</code>
       */
      public Builder clearAutoRefreshTimes() {
        
        autoRefreshTimes_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> completeMissionId_ = java.util.Collections.emptyList();
      private void ensureCompleteMissionIdIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          completeMissionId_ = new java.util.ArrayList<java.lang.Integer>(completeMissionId_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <pre>
       *完成任务id
       * </pre>
       *
       * <code>repeated int32 completeMissionId = 5;</code>
       */
      public java.util.List<java.lang.Integer>
          getCompleteMissionIdList() {
        return java.util.Collections.unmodifiableList(completeMissionId_);
      }
      /**
       * <pre>
       *完成任务id
       * </pre>
       *
       * <code>repeated int32 completeMissionId = 5;</code>
       */
      public int getCompleteMissionIdCount() {
        return completeMissionId_.size();
      }
      /**
       * <pre>
       *完成任务id
       * </pre>
       *
       * <code>repeated int32 completeMissionId = 5;</code>
       */
      public int getCompleteMissionId(int index) {
        return completeMissionId_.get(index);
      }
      /**
       * <pre>
       *完成任务id
       * </pre>
       *
       * <code>repeated int32 completeMissionId = 5;</code>
       */
      public Builder setCompleteMissionId(
          int index, int value) {
        ensureCompleteMissionIdIsMutable();
        completeMissionId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *完成任务id
       * </pre>
       *
       * <code>repeated int32 completeMissionId = 5;</code>
       */
      public Builder addCompleteMissionId(int value) {
        ensureCompleteMissionIdIsMutable();
        completeMissionId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *完成任务id
       * </pre>
       *
       * <code>repeated int32 completeMissionId = 5;</code>
       */
      public Builder addAllCompleteMissionId(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureCompleteMissionIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, completeMissionId_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *完成任务id
       * </pre>
       *
       * <code>repeated int32 completeMissionId = 5;</code>
       */
      public Builder clearCompleteMissionId() {
        completeMissionId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerShopInfo)
    }

    // @@protoc_insertion_point(class_scope:PlayerShopInfo)
    private static final protocol.ShopDB.PlayerShopInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new protocol.ShopDB.PlayerShopInfo();
    }

    public static protocol.ShopDB.PlayerShopInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerShopInfo>
        PARSER = new com.google.protobuf.AbstractParser<PlayerShopInfo>() {
      public PlayerShopInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PlayerShopInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerShopInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerShopInfo> getParserForType() {
      return PARSER;
    }

    public protocol.ShopDB.PlayerShopInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_Shop_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_Shop_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DB_Shop_ShopInfoEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DB_Shop_ShopInfoEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerShopInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerShopInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerShopInfo_BuyRecordEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerShopInfo_BuyRecordEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014ShopDB.proto\032\nShop.proto\"u\n\007DB_Shop\022(\n" +
      "\010shopInfo\030\001 \003(\0132\026.DB_Shop.ShopInfoEntry\032" +
      "@\n\rShopInfoEntry\022\013\n\003key\030\001 \001(\005\022\036\n\005value\030\002" +
      " \001(\0132\017.PlayerShopInfo:\0028\001\"\353\001\n\016PlayerShop" +
      "Info\022\027\n\017nextRefreshTime\030\001 \001(\003\022\032\n\022manualR" +
      "efreshTimes\030\002 \001(\005\0221\n\tbuyRecord\030\003 \003(\0132\036.P" +
      "layerShopInfo.BuyRecordEntry\022\030\n\020autoRefr" +
      "eshTimes\030\004 \001(\005\022\031\n\021completeMissionId\030\005 \003(" +
      "\005\032<\n\016BuyRecordEntry\022\013\n\003key\030\001 \001(\005\022\031\n\005valu" +
      "e\030\002 \001(\0132\n.GoodsInfo:\0028\001B\033\n\010protocol\252\002\016ET",
      "Hotfix.Protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          protocol.Shop.getDescriptor(),
        }, assigner);
    internal_static_DB_Shop_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DB_Shop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_Shop_descriptor,
        new java.lang.String[] { "ShopInfo", });
    internal_static_DB_Shop_ShopInfoEntry_descriptor =
      internal_static_DB_Shop_descriptor.getNestedTypes().get(0);
    internal_static_DB_Shop_ShopInfoEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DB_Shop_ShopInfoEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_PlayerShopInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_PlayerShopInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerShopInfo_descriptor,
        new java.lang.String[] { "NextRefreshTime", "ManualRefreshTimes", "BuyRecord", "AutoRefreshTimes", "CompleteMissionId", });
    internal_static_PlayerShopInfo_BuyRecordEntry_descriptor =
      internal_static_PlayerShopInfo_descriptor.getNestedTypes().get(0);
    internal_static_PlayerShopInfo_BuyRecordEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerShopInfo_BuyRecordEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    protocol.Shop.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
