-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0KvcBNhWB5qbxXZj
EBINgP8P3PYVNNLfrK9H/MWMWpOgCgYIKoZIzj0DAQehRANCAAT7wvxVr7btDwj7
rU02bNFKsnRkzAD5xubE5Nk3j1MdTyClSiJDdQgzsx3MHDqp5DsP4Ls5UKXU1/aR
KUBCWXGV
-----END PRIVATE KEY-----